### ISSUE TITLE
SEGFAULT on v0.4.x and MySQL 8.x

### ISSUE THREAD

**Issue by disordered** [brianmario/mysql2#1008]
I haven't tried all version combinations but the ones I tried seem to produce a segfault on result read.
In case it changes anything both the application and mysql are running inside docker containers.
Ruby backtrace:
```
-- Ruby level backtrace information ----------------------------------------
/usr/local/rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:24:in `<main>'
/usr/local/rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.2.7/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.7/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.2.7/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/ruby/2.2.0/bin/rake:23:in `<top (required)>'
/app/vendor/ruby/2.2.0/bin/rake:23:in `load'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.7/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/app/vendor/ruby/2.2.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `call'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `new'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:950:in `initialize'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:42:in `initialize_schema_migrations_table'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:405:in `charset'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:621:in `show_variable'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `exec_query'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `to_a'
/app/vendor/ruby/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `each'
```
C backtrace:
```
-- C level backtrace information -------------------------------------------
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_vm_bugreport+0x51f) [0x7efcc662ac3f] vm_dump.c:697
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_bug_context+0xcb) [0x7efcc64bcf0b] error.c:425
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(sigsegv+0x3e) [0x7efcc659ec4e] signal.c:879
/lib64/libpthread.so.0 [0x7efcc622f870]
[0x7efcc65a75a0]
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(st_lookup+0x22) [0x7efcc65a7c62] st.c:388
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_enc_find_index+0x38) [0x7efcc64afd38] encoding.c:626
/app/vendor/ruby/2.2.0/gems/mysql2-0.4.10/lib/mysql2/mysql2.so(rb_mysql_result_fetch_row+0x143) [0x7efcc0291653] result.c:228
/app/vendor/ruby/2.2.0/gems/mysql2-0.4.10/lib/mysql2/mysql2.so(rb_mysql_result_each+0x417) [0x7efcc0291107] result.c:834
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call0_body.constprop.79+0x28f) [0x7efcc661fb5f] vm_eval.c:127
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_call0+0x1ba) [0x7efcc66207ba] vm_eval.c:59
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_iterate+0xf4) [0x7efcc6614b44] vm_eval.c:1136
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_block_call+0x2b) [0x7efcc6614cab] vm_eval.c:1205
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(enum_to_a+0x38) [0x7efcc64b1be8] enum.c:503
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call0_body.constprop.79+0x1a5) [0x7efcc661fa75] vm_eval.c:180
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_call0+0x1ba) [0x7efcc66207ba] vm_eval.c:59
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_class_new_instance+0x21) [0x7efcc652b3a1] object.c:1862
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(invoke_block_from_c+0x2f6) [0x7efcc6621866] vm.c:818
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_invoke_proc+0xe0) [0x7efcc6621b30] vm.c:883
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_vm_invoke_proc+0x1a) [0x7efcc6621bea] vm.c:902
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(proc_call+0x52) [0x7efcc64cc432] proc.c:736
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_yield+0x497) [0x7efcc66253a7] vm.c:818
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_ary_each+0x52) [0x7efcc646e8e2] array.c:1814
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x12f8) [0x7efcc6619818] insns.def:1039
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_yield+0x497) [0x7efcc66253a7] vm.c:818
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_ary_each+0x52) [0x7efcc646e8e2] array.c:1814
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x12f8) [0x7efcc6619818] insns.def:1039
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_iseq_eval+0x1a6) [0x7efcc661f606] vm.c:1672
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_load_internal0+0x117) [0x7efcc64c8397] load.c:612
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_f_load+0x86) [0x7efcc64c8b06] load.c:642
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_iseq_eval+0x1a6) [0x7efcc661f606] vm.c:1672
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_load_internal0+0x117) [0x7efcc64c8397] load.c:612
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_f_load+0x86) [0x7efcc64c8b06] load.c:642
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_iseq_eval+0x1a6) [0x7efcc661f606] vm.c:1672
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_load_internal0+0x117) [0x7efcc64c8397] load.c:612
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_f_load+0x86) [0x7efcc64c8b06] load.c:642
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(eval_string_with_cref+0x464) [0x7efcc661edb4] vm_eval.c:1335
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_f_eval+0x7f) [0x7efcc661f33f] vm_eval.c:1374
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_cfunc+0x11e) [0x7efcc6612b1e] vm_insnhelper.c:1380
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_call_method+0x11e) [0x7efcc662907e] vm_insnhelper.c:1689
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec_core+0x2613) [0x7efcc661ab33] insns.def:1069
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(vm_exec+0x82) [0x7efcc661e1c2] vm.c:1440
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(rb_iseq_eval_main+0x1f3) [0x7efcc661f873] vm.c:1685
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(ruby_exec_internal+0xc4) [0x7efcc64c2944] eval.c:254
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(ruby_exec_node+0x1d) [0x7efcc64c4a7d] eval.c:319
/usr/local/rvm/rubies/ruby-2.2.7/lib/libruby.so.2.2(ruby_run_node+0x1c) [0x7efcc64c72ec] eval.c:311
/usr/local/rvm/rubies/ruby-2.2.7/bin/ruby(main+0x4b) [0x40094b] main.c:36
```

**Comment by sodabrew** [comment]
This is a known issue that is fixed is mysql2 gem 0.5.x versions, there are additional encodings in MySQL 8 that are not supported in the 0.4.x gem series. Please upgrade.

**Comment by disordered** [comment]
We are in the process of doing it, but turns out not as simple. Either way, thanks for reply.

**Comment by hobberwickey** [comment]
Is version 5.x compatible with mysql version 5.5?

**Comment by sodabrew** [comment]
The latest version of the gem is compatible with MySQL 5.5, yes. This is explicitly part of the test matrix: https://github.com/brianmario/mysql2/blob/master/.travis.yml#L57
