### ISSUE TITLE
Invalid date in field

### ISSUE THREAD

**Issue by jcpny1** [brianmario/mysql2#1009]
I'm working with a legacy database and am getting this error:
```
Mysql2::Error (Invalid date in field 'REFERRAL_UPDATE_TIME': 0000-00-00 00:00:01):

activerecord (5.2.1) lib/active_record/connection_adapters/mysql/database_statements.rb:34:in `each'
activerecord (5.2.1) lib/active_record/connection_adapters/mysql/database_statements.rb:34:in `to_a'
activerecord (5.2.1) lib/active_record/connection_adapters/mysql/database_statements.rb:34:in `block in exec_query'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
```

I think I've tracked it down to this code (which is in two places in mysql2/result.c, one for DATE and one for DATETIME):
```
            if (month < 1 || day < 1) {
              rb_raise(cMysql2Error, "Invalid date in field '%.*s': %s", fields[i].name_length, fields[i].name, row[i]);
              val = Qnil;
            } else {
```
From the appearance of the code, it seems like I could get back a null value, but instead am getting an exception.
Is there a way to have invalid dates be returned as a null value and just generate a warning (or not) instead of an exception?
This particular issue is arising in the Devise gem during login, that prevents the user from logging in.
I suppose I could alter the Devise code to work around this, but that seems like a bad idea.
Additionally, I'm going to run into this problem in lots of other tables.
Active legacy apps treat the invalid date as meaningful, so updating the data (or the legacy apps) is not doable.

**Comment by sodabrew** [comment]
Returning `nil` for an invalid date would make it impossible to differentiate a null or zero from an invalid value. I'm not sure what the right behavior would be, but as this is specific to your use case I would suggest to hack up a PR on how you want this to look and we can discuss from there.

**Comment by mattbaron** [comment]
I'm having this issue too.  

If you do an insert with an invalid date, mysql will not error out.  Instead it will convert it to a "zero" date.

According to MySQL, it makes perfect sense to convert zero dates to nil.

_The special “zero” date '0000-00-00' can be stored and retrieved as '0000-00-00'. When a '0000-00-00' date is used through Connector/ODBC, it is automatically converted to NULL because ODBC cannot handle that kind of date._

https://dev.mysql.com/doc/refman/8.0/en/using-date.html

Furthermore, the MySQL doc says this:

_MySQL permits you to store dates where the day or month and day are zero. This is convenient if you want to store a birthdate in a DATE column and you know only part of the date._

The code cited by @jcpny1 looks like it errors out when month or date are zero, despite it being a valid date in MySQL.

```
mysql> insert into foo values('2010-00-00 15:03:20');
Query OK, 1 row affected (0.08 sec)

mysql> select * from foo;
+---------------------+
| bar                 |
+---------------------+
| 2019-03-07 16:48:09 |
| NULL                |
| 2010-00-00 15:03:20 |
+---------------------+
3 rows in set (0.00 sec)

mysql> 

```

Casting the values based on the data type in MySQL sounds good, but it just seems to problematic with dates.  I see there is an option to turn off casting, but I just don't understand why this option isn't allowed with prepared statements....

**Comment by nhh** [comment]
+1

**Comment by nhh** [comment]
Finally resolved it with string comparison:

```
UPDATE _table_ SET _column_ = '1970-01-01' where DATE_FORMAT(_column_, '%Y-%m-%d') = '2030-11-00';
```

Step by step the error gone away.
