### ISSUE TITLE
ISO-8601 and typeCast

### ISSUE THREAD

**Issue by ericmaicon** [brianmario/mysql2#1086]
Hey there, I tried to find this same question here, but I am unable to find it. Basically I have DATE and DATETIME on my DB. I can treat fine the DATE field by using moment inside of typeCast function. When I try to do the same with DATETIME, the code simply crashes. Not sure why yet.

You might see below my connection code:
```
 connection: {
      typeCast: (field: any, next: any) => {
        switch (field.type) {
          case 'LONGLONG':
          case 'LONG':
          case 'TINY':
            if (field.length === 1) {
              return field.string() === '1';
            }
            break;
          case 'DATETIME':
            console.log(field.string());
            break;
          case 'DATE':
            if (IsEmpty(field.string())) {
              return null;
            }
            const date = moment(field.string());
            if (date.isValid()) {
              return date.format('YYYY-MM-DDTHH:mm:ssZZ');
            }
            break;
          case 'NEWDECIMAL':
            return parseFloat(field.string());
        }
        return next();
      },
    },
```

the `console.log(field.string());` break just by trying to access string(). If I comment, the code works.

The error:
```Error: Should not reach here: undefined
      at Packet.readLengthCodedNumberExt (/server/node_modules/mysql2/lib/packets/packet.js:227:11)
      at Packet.readLengthCodedNumber (/server/node_modules/mysql2/lib/packets/packet.js:188:17)
      at Packet.readLengthCodedString (/server/node_modules/mysql2/lib/packets/packet.js:369:22)
      at eval (eval at line.toFunction (/server/node_modules/generate-function/index.js:172:21), <anonymous>:156:165)
      at Object.typeCast (/server/.webpack/service/src/service/user/handler/webpack:/src/component/db/DBManager.ts:45:16)
      at new TextRow (eval at line.toFunction (/server/node_modules/generate-function/index.js:172:21), <anonymous>:156:45)
      at Query.row (/server/node_modules/mysql2/lib/commands/query.js:230:17)
      at Query.execute (/server/node_modules/mysql2/lib/commands/command.js:39:22)
      at Connection.handlePacket (/server/node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.Connection.packetParser.p [as onPacket] (/server/node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.Connection.stream.on.data (/server/node_modules/mysql2/lib/connection.js:77:25)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at addChunk (_stream_readable.js:287:12)
      at readableAddChunk (_stream_readable.js:268:11)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Where is the error here? I am blinded right now. 
Thanks in advance

**Comment by sodabrew** [comment]
This doesn’t look like Ruby. Perhaps you mean to find the Nodejs mysql2.
