### ISSUE TITLE
Installation failing on Mac Catalina and Rails 6

### ISSUE THREAD

**Issue by denaliai-dev** [brianmario/mysql2#1106]
Mac Catalina
Rails 6.0.21
Ruby 2.7.0

I am trying to install Rails 6.0.21 on my Mac (Catalina), with Ruby 2.7.0

The installation seems to finish fine. I generated a basic application, with MySQL, but when I tried to start the server, as follows:

    rails s

I got the following error message:

    Traceback (most recent call last):
    	46: from bin/rails:9:in `<main>'
    	45: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
    	44: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
    	43: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
    	42: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    	41: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    	40: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	39: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    	38: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    	37: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
    	36: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
    	35: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
    	34: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
    	33: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
    	32: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
    	31: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
    	30: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
    	29: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
    	28: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
    	27: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
    	26: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
    	25: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    	24: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    	23: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	22: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    	21: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    	20: from /Users/jkmac/Dropbox/jk/development/pck_2/config/application.rb:20:in `<main>'
    	19: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler.rb:174:in `require'
    	18: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
    	17: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
    	16: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
    	15: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
    	14: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
    	13: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    	12: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    	11: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	10: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    	 9: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
    	 8: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<main>'
    	 7: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
    	 6: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
    	 5: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
    	 4: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
    	 3: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
    	 2: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
    	 1: from /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
    /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': dlopen(/Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 9): Library not loaded: libssl.1.0.0.dylib (LoadError)
      Referenced from: /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
      Reason: image not found - /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle

Looking at this last line, when I do:

    ls -l /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle

I get:

    -rwxr-xr-x  1 jkmac  staff  90240 Jan 27 19:00 /Users/jkmac/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle

This is my Gemfile:
    
    
    source 'https://rubygems.org'
    git_source(:github) { |repo| "https://github.com/#{repo}.git" }
    ruby '2.7.0'
    gem 'rails', '6.0.2.1'
    gem 'mysql2', '>= 0.4.4', '< 0.6.0'
    gem 'puma', '~> 4.1'
    gem 'sass-rails', '>= 6'
    gem 'webpacker', '~> 4.0'
    gem 'turbolinks', '~> 5'
    gem 'jbuilder', '~> 2.7'
    gem 'bootsnap', '>= 1.4.2', require: false
    
    group :development, :test do
      gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
    end
    
    group :development do
      gem 'web-console', '>= 3.3.0'
      gem 'listen', '>= 3.0.5', '< 3.2'
    end
    

Here's the output of bundle install:

    The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
    he dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
    Using rake 13.0.1
    Using concurrent-ruby 1.1.5
    Using i18n 1.8.2
    Using minitest 5.14.0
    Using thread_safe 0.3.6
    Using tzinfo 1.2.6
    Using zeitwerk 2.2.2
    Using activesupport 6.0.2.1
    Using builder 3.2.4
    Using erubi 1.9.0
    Using mini_portile2 2.4.0
    Using nokogiri 1.10.7
    Using rails-dom-testing 2.0.3
    Using crass 1.0.6
    Using loofah 2.4.0
    Using rails-html-sanitizer 1.3.0
    Using actionview 6.0.2.1
    Using rack 2.1.2
    Using rack-test 1.1.0
    Using actionpack 6.0.2.1
    Using nio4r 2.5.2
    Using websocket-extensions 0.1.4
    Using websocket-driver 0.7.1
    Using actioncable 6.0.2.1
    Using globalid 0.4.2
    Using activejob 6.0.2.1
    Using activemodel 6.0.2.1
    Using activerecord 6.0.2.1
    Using mimemagic 0.3.4
    Using marcel 0.3.3
    Using activestorage 6.0.2.1
    Using mini_mime 1.0.2
    Using mail 2.7.1
    Using actionmailbox 6.0.2.1
    Using actionmailer 6.0.2.1
    Using actiontext 6.0.2.1
    Using bindex 0.8.1
    Using msgpack 1.3.1
    Using bootsnap 1.4.5
    Using bundler 2.1.2
    Using byebug 11.1.1
    Using ffi 1.12.1
    Using jbuilder 2.9.1
    Using rb-fsevent 0.10.3
    Using rb-inotify 0.10.1
    Using ruby_dep 1.5.0
    Using listen 3.1.5
    Using method_source 0.9.2
    Using mysql2 0.5.3
    Using puma 4.3.1
    Using rack-proxy 0.6.5
    Using thor 1.0.1
    Using railties 6.0.2.1
    Using sprockets 4.0.0
    Using sprockets-rails 3.2.1
    Using rails 6.0.2.1
    Using sassc 2.2.1
    Using tilt 2.0.10
    Using sassc-rails 2.1.2
    Using sass-rails 6.0.0
    Using turbolinks-source 5.2.0
    Using turbolinks 5.2.1
    Using web-console 4.0.1
    Using webpacker 4.2.2
    Bundle complete! 12 Gemfile dependencies, 64 gems now installed.
    Use `bundle info [gemname]` to see where a bundled gem is installed.

Any ideas what's going on?

**Comment by ayushaayalur** [comment]
Any fix for this? I am having the same issue!

**Comment by ain** [comment]
Make sure to wipe the gem cache! Worked for me.
