### ISSUE TITLE
Ruby 2.7 support

### ISSUE THREAD

**Issue by ain** [brianmario/mysql2#1113]
In addition to #1105, installation also fails on Ubuntu, e.g. on Google App Engine build that is based on the image of `gcr.io/gcp-runtimes/ruby/ubuntu16/generate-dockerfile@sha256:feed21acf09aee94685864e1eed51c08e31b305199553cd3fa04096bc88d45ad`.

Failure log:

```
Step #1: LoadError: libmariadb.so.3: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.7.0/bundler/gems/mysql2-c66eb365a977/lib/mysql2/mysql2.so
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
Step #1: /app/vendor/bundle/ruby/2.7.0/bundler/gems/mysql2-c66eb365a977/lib/mysql2.rb:36:in `<main>'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
Step #1: /app/config/application.rb:13:in `<top (required)>'
Step #1: /app/Rakefile:4:in `require'
Step #1: /app/Rakefile:4:in `<top (required)>'
Step #1: /app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Step #1: /opt/rbenv/versions/2.7.0/bin/bundle:23:in `load'
Step #1: /opt/rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
Step #1: (See full trace by running task with --trace)
```

Reproduced on:

- `0.5.2` (3b9a267)
- `0.5.3` (db6733a)
- `master` (c66eb36)

**Comment by jeremy** [comment]
* Does this occur on Ruby 2.7 only, or 2.6.x as well?
* Does your build environment differ from your runtime? Missing `libmariadb.so.3` suggests LD_LIBRARY_PATH difference.
* Can you reproduce with a standalone Dockerfile to share?

**Comment by ain** [comment]
Thanks for the rather fast response @jeremy.

The answers that I can give you form the back of my head:

- Occurs only on `2.7`, does not occur on `2.6.5`
- No
- Currently not, but we can try if it helps

**Comment by ain** [comment]
Cleaning the gem cache resolved the issue.
