### ISSUE TITLE
Segmentation fault at ruby 2.5.8p224 

### ISSUE THREAD

**Issue by theasteve** [brianmario/mysql2#1121]
I'm currently trying to deploy to AWS Lambda. I'm using Ruby -v 2.5.8 and `mysql2` 0.5.2 version. 

```
FROM lambci/lambda:build-ruby2.5

WORKDIR /var/task

# Install MySQL
RUN yum -y install mysql-devel
RUN gem update bundler
```
The above is the Dockerfile to create the container using the Ruby 2.5 environment. I'm able to install `gem 'mysql2', '0.5.2'` but when I test I get the following error:

```
`/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131: [BUG] Segmentation fault at 0x00005643b5ae0000` I used this [article ](https://medium.com/@hsdeekshith/using-mysql2-gem-in-aws-lambda-for-ruby-7f9456bf2ca5) to deploy. Here are the full logs:

/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131: [BUG] Segmentation fault at 0x00005643b5ae0000
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0045 e:000044 CFUNC  :_query
c:0007 p:0015 s:0039 e:000038 BLOCK  /var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131 [FINISH]
c:0006 p:---- s:0036 e:000035 CFUNC  :handle_interrupt
c:0005 p:0033 s:0031 e:000030 METHOD /var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130
c:0004 p:0013 s:0025 e:000024 METHOD /var/task/my_sql.rb:30
c:0003 p:0091 s:0021 e:000020 METHOD /var/task/lamda_function.rb:14
c:0002 p:0014 s:0007 e:000005 EVAL   -e:1 [FINISH]
c:0001 p:0000 s:0003 E:0015f0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:1:in `<main>'
/var/task/lamda_function.rb:14:in `lambda_handler'
/var/task/my_sql.rb:30:in `get_emails_from_db'
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f30596e939e RBP: 0x0000000000000006 RSP: 0x00007fff56c26978
 RAX: 0x00005643b5ad74b1 RBX: 0x0000000000000030 RCX: 0x0000000000000000
 RDX: 0x0000000056432951 RDI: 0x00005643b5adffd0 RSI: 0x00005643b5abbf81
  R8: 0x00005643b5ad74b1  R9: 0x0000000001800000 R10: 0x000000000000006a
 R11: 0x00007f3059720c70 R12: 0x0000000000000300 R13: 0x00005643b5ad72b0
 R14: 0x000000005643b570 R15: 0x00005643b5ad74b1 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/var/lang/bin/ruby(rb_vm_bugreport+0x528) [0x5643b4a2e258] vm_dump.c:703
/var/lang/bin/ruby(rb_bug_context+0xd0) [0x5643b4892680] error.c:589
/var/lang/bin/ruby(sigsegv+0x42) [0x5643b4995bd2] signal.c:928
/lib64/libpthread.so.0(0x7f305a323600) [0x7f305a323600]
/lib64/libc.so.6(__memcpy_ssse3_back+0x193e) [0x7f30596e939e]
/usr/lib64/mysql/libmysqlclient.so.18(0x7f3051728605) [0x7f3051728605]
/usr/lib64/mysql/libmysqlclient.so.18(0x7f3051729515) [0x7f3051729515]
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(nogvl_read_query_result+0x9) [0x7f3051beb489] client.c:529
/var/lang/bin/ruby(rb_thread_call_without_gvl+0x3f) [0x5643b49d97ff] thread.c:1353
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(rb_mysql_client_async_result+0x5c) [0x7f3051bee06c] client.c:576
/var/lang/bin/ruby(rb_ensure+0xca) [0x5643b489e2da] eval.c:1038
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(rb_mysql_query+0x160) [0x7f3051becff0] client.c:792
/var/lang/bin/ruby(vm_call_cfunc+0x106) [0x5643b4a0fe16] vm_insnhelper.c:1918
/var/lang/bin/ruby(vm_call_general+0xe3) [0x5643b4a20363] vm_insnhelper.c:2384
/var/lang/bin/ruby(vm_exec_core+0x2366) [0x5643b4a17196] insns.def:915
/var/lang/bin/ruby(vm_exec+0x89) [0x5643b4a1c1a9] vm.c:1778
/var/lang/bin/ruby(invoke_iseq_block_from_c+0x478) [0x5643b4a1ced8] vm.c:979
/var/lang/bin/ruby(rb_yield+0xdc) [0x5643b4a1d65c] vm.c:1049
/var/lang/bin/ruby(rb_thread_s_handle_interrupt+0x11d) [0x5643b49d5fcd] thread.c:1915
/var/lang/bin/ruby(vm_call_cfunc+0x106) [0x5643b4a0fe16] vm_insnhelper.c:1918
/var/lang/bin/ruby(vm_call_general+0xe3) [0x5643b4a20363] vm_insnhelper.c:2384
/var/lang/bin/ruby(vm_exec_core+0x2f33) [0x5643b4a17d63] insns.def:850
/var/lang/bin/ruby(vm_exec+0x89) [0x5643b4a1c1a9] vm.c:1778
/var/lang/bin/ruby(ruby_exec_internal+0xc5) [0x5643b4899055] eval.c:247
/var/lang/bin/ruby(ruby_run_node+0x2d) [0x5643b489d32d] eval.c:311
/var/lang/bin/ruby(main+0x4b) [0x5643b481294b] addr2line.c:187
*** Error in `ruby': free(): invalid next size (fast): 0x00005643b5ad9900 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x816e9)[0x7f30596146e9]
ruby(+0x249c2c)[0x5643b4a37c2c]
ruby(+0x240266)[0x5643b4a2e266]
ruby(+0xa4680)[0x5643b4892680]
ruby(+0x1a7bd2)[0x5643b4995bd2]
/lib64/libpthread.so.0(+0xf600)[0x7f305a323600]
/lib64/libc.so.6(+0x15639e)[0x7f30596e939e]
/usr/lib64/mysql/libmysqlclient.so.18(+0x20605)[0x7f3051728605]
/usr/lib64/mysql/libmysqlclient.so.18(+0x21515)[0x7f3051729515]
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(+0x6489)[0x7f3051beb489]
ruby(rb_thread_call_without_gvl+0x3f)[0x5643b49d97ff]
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(+0x906c)[0x7f3051bee06c]
ruby(rb_ensure+0xca)[0x5643b489e2da]
/var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so(+0x7ff0)[0x7f3051becff0]
ruby(+0x221e16)[0x5643b4a0fe16]
ruby(+0x232363)[0x5643b4a20363]
ruby(+0x229196)[0x5643b4a17196]
ruby(+0x22e1a9)[0x5643b4a1c1a9]
ruby(+0x22eed8)[0x5643b4a1ced8]
ruby(rb_yield+0xdc)[0x5643b4a1d65c]
ruby(+0x1e7fcd)[0x5643b49d5fcd]
ruby(+0x221e16)[0x5643b4a0fe16]
ruby(+0x232363)[0x5643b4a20363]
ruby(+0x229d63)[0x5643b4a17d63]
ruby(+0x22e1a9)[0x5643b4a1c1a9]
ruby(+0xab055)[0x5643b4899055]
ruby(ruby_run_node+0x2d)[0x5643b489d32d]
ruby(+0x2494b)[0x5643b481294b]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f30595b5575]
ruby(+0x24979)[0x5643b4812979]
======= Memory map: ========
5643b47ee000-5643b4b15000 r-xp 00000000 08:01 2366088                    /var/lang/bin/ruby
5643b4d14000-5643b4d1a000 rw-p 00326000 08:01 2366088                    /var/lang/bin/ruby
5643b4d1a000-5643b4d2c000 rw-p 00000000 00:00 0 
5643b4e23000-5643b5ae0000 rw-p 00000000 00:00 0                          [heap]
7f3048000000-7f3048021000 rw-p 00000000 00:00 0 
7f3048021000-7f304c000000 ---p 00000000 00:00 0 
7f304c4da000-7f304c7b3000 r--s 00000000 08:01 664982                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7f304c7b3000-7f304c9c7000 r--s 00000000 08:01 2365830                    /lib64/libc-2.17.so
7f304c9c7000-7f304da13000 r--s 00000000 08:01 2366088                    /var/lang/bin/ruby
7f304da13000-7f304da19000 r-xp 00000000 08:01 2365864                    /lib64/libnss_dns-2.17.so
7f304da19000-7f304dc18000 ---p 00006000 08:01 2365864                    /lib64/libnss_dns-2.17.so
7f304dc18000-7f304dc19000 r--p 00005000 08:01 2365864                    /lib64/libnss_dns-2.17.so
7f304dc19000-7f304dc1a000 rw-p 00006000 08:01 2365864                    /lib64/libnss_dns-2.17.so
7f304dc1a000-7f304dc1b000 r-xp 00000000 08:01 2366969                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/md5.so
7f304dc1b000-7f304de1a000 ---p 00001000 08:01 2366969                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/md5.so
7f304de1a000-7f304de1b000 rw-p 00000000 08:01 2366969                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/md5.so
7f304de1b000-7f304de2c000 r-xp 00000000 08:01 2367066                    /var/lang/lib/ruby/2.5.0/x86_64-linux/zlib.so
7f304de2c000-7f304e02b000 ---p 00011000 08:01 2367066                    /var/lang/lib/ruby/2.5.0/x86_64-linux/zlib.so
7f304e02b000-7f304e02c000 rw-p 00010000 08:01 2367066                    /var/lang/lib/ruby/2.5.0/x86_64-linux/zlib.so
7f304e02c000-7f304e02e000 r-xp 00000000 08:01 2367043                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7f304e02e000-7f304e22d000 ---p 00002000 08:01 2367043                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7f304e22d000-7f304e22e000 rw-p 00001000 08:01 2367043                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/wait.so
7f304e22e000-7f304e259000 r-xp 00000000 08:01 2367062                    /var/lang/lib/ruby/2.5.0/x86_64-linux/socket.so
7f304e259000-7f304e458000 ---p 0002b000 08:01 2367062                    /var/lang/lib/ruby/2.5.0/x86_64-linux/socket.so
7f304e458000-7f304e459000 rw-p 0002a000 08:01 2367062                    /var/lang/lib/ruby/2.5.0/x86_64-linux/socket.so
7f304e459000-7f304e45a000 rw-p 00000000 00:00 0 
7f304e45a000-7f304e45b000 r-xp 00000000 08:01 2367042                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/nonblock.so
7f304e45b000-7f304e65b000 ---p 00001000 08:01 2367042                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/nonblock.so
7f304e65b000-7f304e65c000 rw-p 00001000 08:01 2367042                    /var/lang/lib/ruby/2.5.0/x86_64-linux/io/nonblock.so
7f304e65c000-7f304e6b1000 r-xp 00000000 08:01 2367050                    /var/lang/lib/ruby/2.5.0/x86_64-linux/openssl.so
7f304e6b1000-7f304e8b1000 ---p 00055000 08:01 2367050                    /var/lang/lib/ruby/2.5.0/x86_64-linux/openssl.so
7f304e8b1000-7f304e8b5000 rw-p 00055000 08:01 2367050                    /var/lang/lib/ruby/2.5.0/x86_64-linux/openssl.so
7f304e8b5000-7f304e8b8000 r-xp 00000000 08:01 2366973                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest.so
7f304e8b8000-7f304eab8000 ---p 00003000 08:01 2366973                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest.so
7f304eab8000-7f304eab9000 rw-p 00003000 08:01 2366973                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest.so
7f304eab9000-7f304eaba000 r-xp 00000000 08:01 2366971                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/sha1.so
7f304eaba000-7f304ecb9000 ---p 00001000 08:01 2366971                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/sha1.so
7f304ecb9000-7f304ecba000 rw-p 00000000 08:01 2366971                    /var/lang/lib/ruby/2.5.0/x86_64-linux/digest/sha1.so
7f304ecba000-7f304ecc6000 r-xp 00000000 08:01 2365866                    /lib64/libnss_files-2.17.so
7f304ecc6000-7f304eec5000 ---p 0000c000 08:01 2365866                    /lib64/libnss_files-2.17.so
7f304eec5000-7f304eec6000 r--p 0000b000 08:01 2365866                    /lib64/libnss_files-2.17.so
7f304eec6000-7f304eec7000 rw-p 0000c000 08:01 2365866                    /lib64/libnss_files-2.17.so
7f304eec7000-7f304eecd000 rw-p 00000000 00:00 0 
7f304eecd000-7f304eece000 ---p 00000000 00:00 0 
7f304eece000-7f304f6ce000 rw-p 00000000 00:00 0 
7f304f6ce000-7f304f6ec000 r-xp 00000000 08:01 2495264                    /usr/lib64/libselinux.so.1
7f304f6ec000-7f304f8eb000 ---p 0001e000 08:01 2495264                    /usr/lib64/libselinux.so.1
7f304f8eb000-7f304f8ec000 r--p 0001d000 08:01 2495264                    /usr/lib64/libselinux.so.1
7f304f8ec000-7f304f8ed000 rw-p 0001e000 08:01 2495264                    /usr/lib64/libselinux.so.1
7f304f8ed000-7f304f8ef000 rw-p 00000000 00:00 0 
7f304f8ef000-7f304f905000 r-xp 00000000 08:01 2365882                    /lib64/libresolv-2.17.so
7f304f905000-7f304fb04000 ---p 00016000 08:01 2365882                    /lib64/libresolv-2.17.so
7f304fb04000-7f304fb05000 r--p 00015000 08:01 2365882                    /lib64/libresolv-2.17.so
7f304fb05000-7f304fb06000 rw-p 00016000 08:01 2365882                    /lib64/libresolv-2.17.so
7f304fb06000-7f304fb08000 rw-p 00000000 00:00 0 
7f304fb08000-7f304fb0b000 r-xp 00000000 08:01 2493159                    /lib64/libkeyutils.so.1.5
7f304fb0b000-7f304fd0a000 ---p 00003000 08:01 2493159                    /lib64/libkeyutils.so.1.5
7f304fd0a000-7f304fd0b000 rw-p 00002000 08:01 2493159                    /lib64/libkeyutils.so.1.5
7f304fd0b000-7f304fd19000 r-xp 00000000 08:01 2495200                    /usr/lib64/libkrb5support.so.0.1
7f304fd19000-7f304ff19000 ---p 0000e000 08:01 2495200                    /usr/lib64/libkrb5support.so.0.1
7f304ff19000-7f304ff1a000 r--p 0000e000 08:01 2495200                    /usr/lib64/libkrb5support.so.0.1
7f304ff1a000-7f304ff1b000 rw-p 0000f000 08:01 2495200                    /usr/lib64/libkrb5support.so.0.1
7f304ff1b000-7f304ff4b000 r-xp 00000000 08:01 2495188                    /usr/lib64/libk5crypto.so.3.1
7f304ff4b000-7f305014b000 ---p 00030000 08:01 2495188                    /usr/lib64/libk5crypto.so.3.1
7f305014b000-7f305014d000 r--p 00030000 08:01 2495188                    /usr/lib64/libk5crypto.so.3.1
7f305014d000-7f305014e000 rw-p 00032000 08:01 2495188                    /usr/lib64/libk5crypto.so.3.1
7f305014e000-7f3050151000 r-xp 00000000 08:01 2494900                    /usr/lib64/libcom_err.so.2.1
7f3050151000-7f3050350000 ---p 00003000 08:01 2494900                    /usr/lib64/libcom_err.so.2.1
7f3050350000-7f3050351000 rw-p 00002000 08:01 2494900                    /usr/lib64/libcom_err.so.2.1
7f3050351000-7f305042a000 r-xp 00000000 08:01 2495198                    /usr/lib64/libkrb5.so.3.3
7f305042a000-7f3050629000 ---p 000d9000 08:01 2495198                    /usr/lib64/libkrb5.so.3.3
7f3050629000-7f3050637000 r--p 000d8000 08:01 2495198                    /usr/lib64/libkrb5.so.3.3
7f3050637000-7f305063a000 rw-p 000e6000 08:01 2495198                    /usr/lib64/libkrb5.so.3.3
7f305063a000-7f3050684000 r-xp 00000000 08:01 2495156                    /usr/lib64/libgssapi_krb5.so.2.2
7f3050684000-7f3050884000 ---p 0004a000 08:01 2495156                    /usr/lib64/libgssapi_krb5.so.2.2
7f3050884000-7f3050885000 r--p 0004a000 08:01 2495156                    /usr/lib64/libgssapi_krb5.so.2.2
7f3050885000-7f3050887000 rw-p 0004b000 08:01 2495156                    /usr/lib64/libgssapi_krb5.so.2.2
7f3050887000-7f305089d000 r-xp 00000000 08:01 2493154                    /lib64/libgcc_s-7-20170915.so.1
7f305089d000-7f3050a9c000 ---p 00016000 08:01 2493154                    /lib64/libgcc_s-7-20170915.so.1
7f3050a9c000-7f3050a9d000 rw-p 00015000 08:01 2493154                    /lib64/libgcc_s-7-20170915.so.1
7f3050a9d000-7f3050c12000 r-xp 00000000 08:01 2495276                    /usr/lib64/libstdc++.so.6.0.24
7f3050c12000-7f3050e12000 ---p 00175000 08:01 2495276                    /usr/lib64/libstdc++.so.6.0.24
7f3050e12000-7f3050e1c000 r--p 00175000 08:01 2495276                    /usr/lib64/libstdc++.so.6.0.24
7f3050e1c000-7f3050e1e000 rw-p 0017f000 08:01 2495276                    /usr/lib64/libstdc++.so.6.0.24
7f3050e1e000-7f3050e22000 rw-p 00000000 00:00 0 
7f3050e22000-7f3051054000 r-xp 00000000 08:01 3804459                    /usr/lib64/libcrypto.so.1.0.2k
7f3051054000-7f3051254000 ---p 00232000 08:01 3804459                    /usr/lib64/libcrypto.so.1.0.2k
7f3051254000-7f3051270000 r--p 00232000 08:01 3804459                    /usr/lib64/libcrypto.so.1.0.2k
7f3051270000-7f305127d000 rw-p 0024e000 08:01 3804459                    /usr/lib64/libcrypto.so.1.0.2k
7f305127d000-7f3051281000 rw-p 00000000 00:00 0 
7f3051281000-7f30512e7000 r-xp 00000000 08:01 3804603                    /usr/lib64/libssl.so.1.0.2k
7f30512e7000-7f30514e7000 ---p 00066000 08:01 3804603                    /usr/lib64/libssl.so.1.0.2k
7f30514e7000-7f30514eb000 r--p 00066000 08:01 3804603                    /usr/lib64/libssl.so.1.0.2k
7f30514eb000-7f30514f2000 rw-p 0006a000 08:01 3804603                    /usr/lib64/libssl.so.1.0.2k
7f30514f2000-7f3051507000 r-xp 00000000 08:01 2493232                    /lib64/libz.so.1.2.8
7f3051507000-7f3051706000 ---p 00015000 08:01 2493232                    /lib64/libz.so.1.2.8
7f3051706000-7f3051707000 r--p 00014000 08:01 2493232                    /lib64/libz.so.1.2.8
7f3051707000-7f3051708000 rw-p 00015000 08:01 2493232                    /lib64/libz.so.1.2.8
7f3051708000-7f3051960000 r-xp 00000000 08:01 664982                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7f3051960000-7f3051b5f000 ---p 00258000 08:01 664982                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7f3051b5f000-7f3051be0000 rw-p 00257000 08:01 664982                     /usr/lib64/mysql/libmysqlclient.so.18.0.0
7f3051be0000-7f3051be5000 rw-p 00000000 00:00 0 
7f3051be5000-7f3051bf5000 r-xp 00000000 00:51 12964103663                /var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so
7f3051bf5000-7f3051df5000 ---p 00010000 00:51 12964103663                /var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so
7f3051df5000-7f3051df7000 rw-p 00010000 00:51 12964103663                /var/task/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.so
7f3051df7000-7f3051e0b000 r-xp 00000000 08:01 2366960                    /var/lang/lib/ruby/2.5.0/x86_64-linux/bigdecimal.so
7f3051e0b000-7f305200b000 ---p 00014000 08:01 2366960                    /var/lang/lib/ruby/2.5.0/x86_64-linux/bigdecimal.so
7f305200b000-7f305200c000 rw-p 00014000 08:01 2366960                    /var/lang/lib/ruby/2.5.0/x86_64-linux/bigdecimal.so
7f305200c000-7f3052014000 r-xp 00000000 08:01 2367063                    /var/lang/lib/ruby/2.5.0/x86_64-linux/stringio.so
7f3052014000-7f3052213000 ---p 00008000 08:01 2367063                    /var/lang/lib/ruby/2.5.0/x86_64-linux/stringio.so
7f3052213000-7f3052214000 rw-p 00007000 08:01 2367063                    /var/lang/lib/ruby/2.5.0/x86_64-linux/stringio.so
7f3052214000-7f305221a000 r-xp 00000000 08:01 2367035                    /var/lang/lib/ruby/2.5.0/x86_64-linux/etc.so
7f305221a000-7f3052419000 ---p 00006000 08:01 2367035                    /var/lang/lib/ruby/2.5.0/x86_64-linux/etc.so
7f3052419000-7f305241a000 rw-p 00005000 08:01 2367035                    /var/lang/lib/ruby/2.5.0/x86_64-linux/etc.so
7f305241a000-7f3052450000 r-xp 00000000 08:01 2366965                    /var/lang/lib/ruby/2.5.0/x86_64-linux/date_core.so
7f3052450000-7f305264f000 ---p 00036000 08:01 2366965                    /var/lang/lib/ruby/2.5.0/x86_64-linux/date_core.so
7f305264f000-7f3052651000 rw-p 00035000 08:01 2366965                    /var/lang/lib/ruby/2.5.0/x86_64-linux/date_core.so
7f3052651000-7f3052652000 rw-p 00000000 00:00 0 
7f3052652000-7f305265b000 r-xp 00000000 08:01 3155500                    /var/runtime/gems/json-2.3.0/lib/json/ext/generator.so
7f305265b000-7f305285b000 ---p 00009000 08:01 3155500                    /var/runtime/gems/json-2.3.0/lib/json/ext/generator.so
7f305285b000-7f305285c000 rw-p 00009000 08:01 3155500                    /var/runtime/gems/json-2.3.0/lib/json/ext/generator.so
7f305285c000-7f3052862000 r-xp 00000000 08:01 3155501                    /var/runtime/gems/json-2.3.0/lib/json/ext/parser.so
7f3052862000-7f3052a61000 ---p 00006000 08:01 3155501                    /var/runtime/gems/json-2.3.0/lib/json/ext/parser.so
7f3052a61000-7f3052a62000 rw-p 00005000 08:01 3155501                    /var/runtime/gems/json-2.3.0/lib/json/ext/parser.so
7f3052a62000-7f3052a64000 r-xp 00000000 08:01 2367021                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7f3052a64000-7f3052c64000 ---p 00002000 08:01 2367021                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7f3052c64000-7f3052c65000 rw-p 00002000 08:01 2367021                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/trans/transdb.so
7f3052c65000-7f3052c67000 r-xp 00000000 08:01 2366978                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7f3052c67000-7f3052e66000 ---p 00002000 08:01 2366978                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7f3052e66000-7f3052e67000 rw-p 00001000 08:01 2366978                    /var/lang/lib/ruby/2.5.0/x86_64-linux/enc/encdb.so
7f3052e67000-7f3059391000 r--p 00000000 08:01 3803942                    /usr/lib/locale/locale-archive
7f3059391000-7f3059393000 r-xp 00000000 08:01 2493151                    /lib64/libfreebl3.so
7f3059393000-7f3059592000 ---p 00002000 08:01 2493151                    /lib64/libfreebl3.so
7f3059592000-7f3059593000 rw-p 00001000 08:01 2493151                    /lib64/libfreebl3.so
7f3059593000-7f3059756000 r-xp 00000000 08:01 2365830                    /lib64/libc-2.17.so
7f3059756000-7f3059956000 ---p 001c3000 08:01 2365830                    /lib64/libc-2.17.so
7f3059956000-7f305995a000 r--p 001c3000 08:01 2365830                    /lib64/libc-2.17.so
7f305995a000-7f305995c000 rw-p 001c7000 08:01 2365830                    /lib64/libc-2.17.so
7f305995c000-7f3059961000 rw-p 00000000 00:00 0 
7f3059961000-7f3059a62000 r-xp 00000000 08:01 2365852                    /lib64/libm-2.17.so
7f3059a62000-7f3059c61000 ---p 00101000 08:01 2365852                    /lib64/libm-2.17.so
7f3059c61000-7f3059c62000 r--p 00100000 08:01 2365852                    /lib64/libm-2.17.so
7f3059c62000-7f3059c63000 rw-p 00101000 08:01 2365852                    /lib64/libm-2.17.so
7f3059c63000-7f3059c6b000 r-xp 00000000 08:01 2365836                    /lib64/libcrypt-2.17.so
7f3059c6b000-7f3059e6a000 ---p 00008000 08:01 2365836                    /lib64/libcrypt-2.17.so
7f3059e6a000-7f3059e6b000 r--p 00007000 08:01 2365836                    /lib64/libcrypt-2.17.so
7f3059e6b000-7f3059e6c000 rw-p 00008000 08:01 2365836                    /lib64/libcrypt-2.17.so
7f3059e6c000-7f3059e9a000 rw-p 00000000 00:00 0 
7f3059e9a000-7f3059e9c000 r-xp 00000000 08:01 2365841                    /lib64/libdl-2.17.so
7f3059e9c000-7f305a09c000 ---p 00002000 08:01 2365841                    /lib64/libdl-2.17.so
7f305a09c000-7f305a09d000 r--p 00002000 08:01 2365841                    /lib64/libdl-2.17.so
7f305a09d000-7f305a09e000 rw-p 00003000 08:01 2365841                    /lib64/libdl-2.17.so
7f305a09e000-7f305a113000 r-xp 00000000 08:01 2494959                    /usr/lib64/libgmp.so.10.2.0
7f305a113000-7f305a312000 ---p 00075000 08:01 2494959                    /usr/lib64/libgmp.so.10.2.0
7f305a312000-7f305a314000 rw-p 00074000 08:01 2494959                    /usr/lib64/libgmp.so.10.2.0
7f305a314000-7f305a32b000 r-xp 00000000 08:01 2365880                    /lib64/libpthread-2.17.so
7f305a32b000-7f305a52a000 ---p 00017000 08:01 2365880                    /lib64/libpthread-2.17.so
7f305a52a000-7f305a52b000 r--p 00016000 08:01 2365880                    /lib64/libpthread-2.17.so
7f305a52b000-7f305a52c000 rw-p 00017000 08:01 2365880                    /lib64/libpthread-2.17.so
7f305a52c000-7f305a530000 rw-p 00000000 00:00 0 
7f305a530000-7f305a552000 r-xp 00000000 08:01 2365819                    /lib64/ld-2.17.so
7f305a5b8000-7f305a5b9000 rw-p 00000000 00:00 0 
7f305a5b9000-7f305a5dd000 r--s 00000000 08:01 2365880                    /lib64/libpthread-2.17.so
7f305a5dd000-7f305a63e000 rw-p 00000000 00:00 0 
7f305a63e000-7f305a645000 r--s 00000000 08:01 3804379                    /usr/lib64/gconv/gconv-modules.cache
7f305a645000-7f305a646000 ---p 00000000 00:00 0 
7f305a646000-7f305a751000 rw-p 00000000 00:00 0 
7f305a751000-7f305a752000 r--p 00021000 08:01 2365819                    /lib64/ld-2.17.so
7f305a752000-7f305a753000 rw-p 00022000 08:01 2365819                    /lib64/ld-2.17.so
7f305a753000-7f305a754000 rw-p 00000000 00:00 0 
7fff5642a000-7fff56c29000 rw-p 00000000 00:00 0                          [stack]
7fff56dd0000-7fff56dd2000 r--p 00000000 00:00 0                          [vvar]
7fff56dd2000-7fff56dd4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted
```

**Comment by metaskills** [comment]
Sharing this Mysql2 Lambda gem project if anyone is interested. https://github.com/customink/mysql2-lambda
