### ISSUE TITLE
Library not loaded: libssl.1.1.dylib

### ISSUE THREAD

**Issue by josephmo** [brianmario/mysql2#1128]
OS: Mac Catalina 10.15.5
Rails: 6.0.2.2
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

In my Gemfile, I have:

gem 'mysql2', '0.5.3'

When I do bundle, install, it seems as if everything is fine, and then I get the following error message:

Error:[rake --tasks] rake aborted!
LoadError: dlopen(/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 9): Library not loaded: libssl.1.1.dylib
Referenced from: /Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
Reason: image not found - /Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `block in require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:325:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<main>'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler.rb:174:in `require'
/Users/my-mac/Dropbox/my/development/training/educate-learning-rails-app-theme/config/application.rb:11:in `<top (required)>'
/Users/my-mac/Dropbox/my/development/training/educate-learning-rails-app-theme/Rakefile:4:in `require_relative'
/Users/my-mac/Dropbox/my/development/training/educate-learning-rails-app-theme/Rakefile:4:in `<top (required)>'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/my-mac/.rbenv/versions/2.7.1/bin/rake:23:in `load'
/Users/my-mac/.rbenv/versions/2.7.1/bin/rake:23:in `<top (required)>'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/my-mac/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/Users/my-mac/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/my-mac/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'

I made sure that xcode command like tools are installed and up to date

Any ideas?

**Comment by mein-beer-hu** [comment]
I have the same issue:
`bundle install` succeeds but, when I run any rails commands (including `rails s`), I get the error this error
```
require': dlopen(/Users/sss/.rvm/gems/ruby-2.7.1/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /usr/local/opt/mysql/lib/libmysqlclient.20.dylib
  Reason: image not found - /Users/sss/.rvm/gems/ruby-2.7.1/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
```

**Comment by afief** [comment]
same here
```dlopen(/Users/afief/.rvm/gems/ruby-2.5.5@webauto/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/opt/mysql/lib/libmysqlclient.21.dylib
  Reason: image not found - /Users/afief/.rvm/gems/ruby-2.5.5@webauto/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle (LoadError)```

**Comment by jeremy** [comment]
See #795

**Comment by josephmo** [comment]
#795 says: xcode-select --install which will install/update xcode. That's up to date on my system (see my issue)

**Comment by sodabrew** [comment]
Resolved by #1204
