### ISSUE TITLE
How to get the result by SQL "STATUS"?

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#1191]
I have a question.
I want to get the result by the SQL command `STATUS` on the `mysql2`. How to get it?
I am using `mysql2` on the latest master + (some patches).

```
$ mysql -h 127.0.0.1 -u root -P 13306 -e STATUS
--------------
mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for Linux (x86_64) using  EditLine wrapper

Connection id:    5
Current database: 
Current user:   root@1049a24b9f6c
SSL:      Not in use
Current pager:    stdout
Using outfile:    ''
Using delimiter:  ;
Server:     MariaDB
Server version:   10.5.9-MariaDB-1:10.5.9+maria~focal mariadb.org binary distribution
Protocol version: 10
Connection:   127.0.0.1 via TCP/IP
Server characterset:  utf8mb4
Db     characterset:  utf8mb4
Client characterset:  utf8
Conn.  characterset:  utf8
TCP port:   13306
Uptime:     37 min 48 sec

Threads: 1  Questions: 18  Slow queries: 0  Opens: 17  Open tables: 10  Queries per second avg: 0.007
--------------

```

Here is the result. The `SELECT 1` is OK.

```
$ bundle exec irb
irb(main):001:0> require 'mysql2'
=> true
irb(main):002:0> client = Mysql2::Client.new(:host => "127.0.0.1", :port => '13306', :username => "root")
=> 
#<Mysql2::Client:0x0000000002900360
...
irb(main):003:0> results = client.query("SELECT 1")
=> 
#<Mysql2::Result:0x000000000286e820
...
irb(main):006:0> row = results.each
=> [{"1"=>1}]
```

But the `STATUS` raises an error.

```
irb(main):007:0> results = client.query("STATUS")
/home/jaruga/git/mysql2_2/lib/mysql2/client.rb:131:in `_query': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'STATUS' at line 1 (Mysql2::Error)
	from /home/jaruga/git/mysql2_2/lib/mysql2/client.rb:131:in `block in query'
	from /home/jaruga/git/mysql2_2/lib/mysql2/client.rb:130:in `handle_interrupt'
	from /home/jaruga/git/mysql2_2/lib/mysql2/client.rb:130:in `query'
	from (irb):7:in `<main>'
	from /home/jaruga/git/mysql2_2/vendor/bundle/ruby/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /home/jaruga/git/mysql2_2/vendor/bundle/ruby/3.0.0/bin/irb:23:in `load'
	from /home/jaruga/git/mysql2_2/vendor/bundle/ruby/3.0.0/bin/irb:23:in `<top (required)>'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli.rb:497:in `exec'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /usr/local/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	... 6 levels...
```

Thanks.

**Comment by sodabrew** [comment]
The `STATUS` command is specific to the `mysql` command-line interface, it's not actually a SQL command sent to the server. You can send `SHOW STATUS` to the server to get server status. Some of those client-side connection values are available in the Client object.

**Comment by junaruga** [comment]
@sodabrew Thanks for the info!

> The STATUS command is specific to the mysql command-line interface, it's not actually a SQL command sent to the server.

I did not know that. Seeing the document in Oracle, the `status` (lowercase) was correct rather than `STATUS`. I keep it in mind.
https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/mysql-commands.html

> You can send SHOW STATUS to the server to get server status.

I actually want to get the following characterset by the `status` by `mysql2` gem to compare the info between each CI cases related to https://github.com/brianmario/mysql2/issues/1152#issuecomment-818539367 .

```
Server characterset:  utf8mb4
Db     characterset:  utf8mb4
Client characterset:  utf8
Conn.  characterset:  utf8
```

Checking the results by `SHOW STATUS`, I could not find values related to the characterset list.
But I could find the following characterset list by `SELECT * FROM information_schema.SCHEMATA` by seeing [this page](https://stackoverflow.com/questions/1049728/how-do-i-see-what-character-set-a-mysql-database-table-column-is). Possibly that is what I want.

```
irb(main):003:0> results = client.query("SELECT * FROM information_schema.SCHEMATA")
=> 
#<Mysql2::Result:0x0000000001b16308
...
irb(main):004:1* results.each do |row|
irb(main):005:1*   puts row
irb(main):006:0> end
{"CATALOG_NAME"=>"def", "SCHEMA_NAME"=>"information_schema", "DEFAULT_CHARACTER_SET_NAME"=>"utf8", "DEFAULT_COLLATION_NAME"=>"utf8_general_ci", "SQL_PATH"=>nil, "SCHEMA_COMMENT"=>""}
{"CATALOG_NAME"=>"def", "SCHEMA_NAME"=>"mysql", "DEFAULT_CHARACTER_SET_NAME"=>"utf8mb4", "DEFAULT_COLLATION_NAME"=>"utf8mb4_general_ci", "SQL_PATH"=>nil, "SCHEMA_COMMENT"=>""}
{"CATALOG_NAME"=>"def", "SCHEMA_NAME"=>"test", "DEFAULT_CHARACTER_SET_NAME"=>"utf8mb4", "DEFAULT_COLLATION_NAME"=>"utf8mb4_general_ci", "SQL_PATH"=>nil, "SCHEMA_COMMENT"=>""}
{"CATALOG_NAME"=>"def", "SCHEMA_NAME"=>"performance_schema", "DEFAULT_CHARACTER_SET_NAME"=>"utf8", "DEFAULT_COLLATION_NAME"=>"utf8_general_ci", "SQL_PATH"=>nil, "SCHEMA_COMMENT"=>""}
=> 
[{"CATALOG_NAME"=>"def",
  "SCHEMA_NAME"=>"information_schema",
  "DEFAULT_CHARACTER_SET_NAME"=>"utf8",
  "DEFAULT_COLLATION_NAME"=>"utf8_general_ci",
  "SQL_PATH"=>nil,
  "SCHEMA_COMMENT"=>""},
 {"CATALOG_NAME"=>"def",
  "SCHEMA_NAME"=>"mysql",
  "DEFAULT_CHARACTER_SET_NAME"=>"utf8mb4",
  "DEFAULT_COLLATION_NAME"=>"utf8mb4_general_ci",
  "SQL_PATH"=>nil,
  "SCHEMA_COMMENT"=>""},
 {"CATALOG_NAME"=>"def",
  "SCHEMA_NAME"=>"test",
  "SCHEMA_COMMENT"=>""},
 {"CATALOG_NAME"=>"def",
  "SCHEMA_NAME"=>"performance_schema",
  "DEFAULT_CHARACTER_SET_NAME"=>"utf8",
  "DEFAULT_COLLATION_NAME"=>"utf8_general_ci",
  "SQL_PATH"=>nil,
  "SCHEMA_COMMENT"=>""}]
```

> Some of those client-side connection values are available in the Client object.

OK. I could see the following connection values in the Client object.

```
irb(main):011:0> client.server_info
=> {:id=>100509, :version=>"10.5.9-MariaDB-1:10.5.9+maria~focal"}

irb(main):012:0> client.encoding
=> #<Encoding:UTF-8>
```

If you know a better SQL or object in the client object to get the chracterset list. please you let me know.
Thanks!
I would close this ticket.

**Comment by junaruga** [comment]
I checked the values by `status` for each database. The value of the `Db     characterset` in the results by the `status` command is equivalent with the `information_schema.SCHEMATA.DEFAULT_CHARACTER_SET_NAME`.

(The information by port 13306 on this issue page) is from MariaDB server executed by the official MariaDB container image `mariadb:10.5-focal`.

```
mysql -h 127.0.0.1 -u root -P 13306 -e status

Server characterset:  utf8mb4
Db     characterset:  utf8mb4
Client characterset:  utf8 
Conn.  characterset:  utf8
```

```
mysql -h 127.0.0.1 -u root -P 13306 -e status mysql

Server characterset:  utf8mb4
Db     characterset:  utf8mb4
Client characterset:  utf8
Conn.  characterset:  utf8
```

```
mysql -h 127.0.0.1 -u root -P 13306 -e status test

Server characterset:  utf8mb4
Db     characterset:  utf8mb4 
Client characterset:  utf8
Conn.  characterset:  utf8
```

```
mysql -h 127.0.0.1 -u root -P 13306 -e status information_schema

Server characterset:  utf8mb4
Db     characterset:  utf8 
Client characterset:  utf8
Conn.  characterset:  utf8
```

```
mysql -h 127.0.0.1 -u root -P 13306 -e status performance_schema

Server characterset:  utf8mb4
Db     characterset:  utf8 
Client characterset:  utf8
Conn.  characterset:  utf8
```
