### ISSUE TITLE
macOS MariaDB 10.5 test failures

### ISSUE THREAD

**Issue by junaruga** [brianmario/mysql2#1194]
This issue ticket is to manage the test failures on GitHub Actions macOS MariaDB 10.5 test failures.

https://github.com/brianmario/mysql2/pull/1193/checks?check_run_id=2363155750#step:9:536

```
  1) Mysql2::EM::Client should support async queries
     Failure/Error: expect(results[0].keys).to include("second_query")
       expected ["first_query"] to include "second_query"
     # ./spec/em/em_spec.rb:26:in `block (2 levels) in <top (required)>'

  2) Mysql2::EM::Client should not raise error when closing client with no query running
     Failure/Error: expect(callbacks_run).to eq([:callback])

       expected: [:callback]
            got: []

       (compared using ==)

       Diff:
       @@ -1 +1 @@
       -[:callback]
       +[]
     # ./spec/em/em_spec.rb:124:in `block (4 levels) in <top (required)>'
     # ./spec/em/em_spec.rb:114:in `block (2 levels) in <top (required)>'

  3) Mysql2::Client#query should be impervious to connection-corrupting timeouts in #execute
     Failure/Error: expect { Timeout.timeout(0.1) { stmt.execute(0.2) } }.to raise_error(Timeout::Error)
       expected Timeout::Error but nothing was raised
     # ./spec/mysql2/client_spec.rb:659:in `block (3 levels) in <top (required)>'

Finished in 13.92 seconds (files took 0.9592 seconds to load)
333 examples, 3 failures, 3 pending
```

The failures **rarely** happens.
For example here is the success case on my forked repository.
https://github.com/junaruga/mysql2/runs/2363101517?check_suite_focus=true

**Comment by junaruga** [comment]
Another case for the failure. It's not rare but sometimes happens.

https://github.com/brianmario/mysql2/runs/2365625101?check_suite_focus=true#step:9:535

```
Failures:

  1) Mysql2::EM::Client should support async queries
     Failure/Error: expect(results[0].keys).to include("second_query")
       expected ["first_query"] to include "second_query"
     # ./spec/em/em_spec.rb:26:in `block (2 levels) in <top (required)>'

Finished in 15.98 seconds (files took 0.76309 seconds to load)
333 examples, 1 failure, 3 pending
```

**Comment by junaruga** [comment]
It seems this issue happens on MacOS mysql case too.
Here is the log on the latest master branch.
https://github.com/brianmario/mysql2/actions/runs/3717583637/jobs/6305086066#step:8:4051

**Comment by sodabrew** [comment]
Resolved by #1473
