### ISSUE TITLE
Mysql2::Error: Got packets out of order

### ISSUE THREAD

**Issue by jstuart-usinternet** [brianmario/mysql2#1217]
I'm getting the following error and I'm not sure if it has to do with mysql2 or delayed_job.  I search through issues and couldn't find an exact match for `Got packets out of order`.

Using:
- mysql2 version 0.4.10; however same error when using 0.5.3
- Rvm with Ruby 2.6.4 
- Ubuntu 20.04

Workflow
- Delayed_job receives a task and inserts initial record into remote database running mariadb 10.4.21.
- Delayed_job task fails given error below and updates 'last_error' column of delayed_jobs table.

Attempted Fix
- I installed mariadb client and installed gem with `--with-mysql-config` that points to the mariadb config.  Result: same error.

Any insight you could provide as to why I'm  getting this error would be appreciated.  Thanks
```
Mysql2::Error: Got packets out of order
/usr/local/rvm/gems/ruby-2.6.4/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/local/rvm/gems/ruby-2.6.4/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/local/rvm/gems/ruby-2.6.4/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/rvm/gems/ruby-2.6.4/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/logging.rb:76:in `block in log_connection_execute'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/logging.rb:45:in `log_connection_yield'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/logging.rb:76:in `log_connection_execute'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/adapters/shared/mysql.rb:390:in `begin_new_transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:320:in `begin_transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/adapters/shared/mysql.rb:399:in `begin_transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:214:in `_transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/model/base.rb:2372:in `checked_transaction'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/model/base.rb:1543:in `block in destroy'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/model/base.rb:2360:in `checked_save_failure'
/usr/local/rvm/gems/ruby-2.6.4/gems/sequel-4.49.0/lib/sequel/model/base.rb:1543:in `destroy'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:231:in `block in run'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:229:in `run'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:213:in `block in work_off'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `times'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `work_off'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `loop'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `block in start'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/worker.rb:171:in `start'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:137:in `run'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:125:in `block in run_process'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/application.rb:277:in `block in start_proc'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/application.rb:281:in `start_proc'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/application.rb:307:in `start'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/controller.rb:56:in `run'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons.rb:199:in `block in run_proc'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons/cmdline.rb:124:in `catch_exceptions'
/usr/local/rvm/gems/ruby-2.6.4/gems/daemons-1.4.1/lib/daemons.rb:198:in `run_proc'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:123:in `run_process'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:104:in `block in daemonize'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:102:in `times'
/usr/local/rvm/gems/ruby-2.6.4/gems/delayed_job-4.1.9/lib/delayed/command.rb:102:in `daemonize'
/usr/local/rvm/gems/ruby-2.6.4/gems/ravon-adhearsion_models-1.12.0/exe/dj_workers_asterisk_user.rb:36:in `<class:CLI>'
/usr/local/rvm/gems/ruby-2.6.4/gems/ravon-adhearsion_models-1.12.0/exe/dj_workers_asterisk_user.rb:23:in `<module:DelayedJob>'
/usr/local/rvm/gems/ruby-2.6.4/gems/ravon-adhearsion_models-1.12.0/exe/dj_workers_asterisk_user.rb:22:in `<module:AdhearsionModels>'
/usr/local/rvm/gems/ruby-2.6.4/gems/ravon-adhearsion_models-1.12.0/exe/dj_workers_asterisk_user.rb:21:in `<module:Ravon>'
/usr/local/rvm/gems/ruby-2.6.4/gems/ravon-adhearsion_models-1.12.0/exe/dj_workers_asterisk_user.rb:20:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.4/bin/dj_workers_asterisk_user.rb:23:in `load'
/usr/local/rvm/gems/ruby-2.6.4/bin/dj_workers_asterisk_user.rb:23:in `<main>'
/usr/local/rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by sodabrew** [comment]
You may be sharing a single connection between multiple threads or child processes; this is OK as long as you manage locking. The mysql2 gem does not have a database connection pool manager built-in, usually people use ActiveRecord for this purpose. I'm not as familiar with Sequel, but it should have something to help manage a connection pool.

**Comment by jstuart-usinternet** [comment]
Thanks, will close for now.
