### ISSUE TITLE
Failure with MariaDB Connector/C 3.2

### ISSUE THREAD

**Issue by pvalena** [brianmario/mysql2#1240]
Hello,

we're testing an upgrade in Fedora to a newer MariaDB Connector/C [1] and the tests fail with the following.

```

  1) Mysql2::Client#query should detect closed connection on query read error
     Failure/Error:
       expect do
         @client.query("SELECT SLEEP(1)")
       end.to raise_error(Mysql2::Error, /Lost connection to MySQL server/)

       expected Mysql2::Error with message matching /Lost connection to MySQL server/, got #<Mysql2::Error::ConnectionError: Lost connection to server during query> with backtrace:
         # ./lib/mysql2/client.rb:131:in `_query'
         # ./lib/mysql2/client.rb:131:in `block in query'
         # ./lib/mysql2/client.rb:130:in `handle_interrupt'
         # ./lib/mysql2/client.rb:130:in `query'
         # ./spec/mysql2/client_spec.rb:575:in `block (4 levels) in <top (required)>'
         # ./spec/mysql2/client_spec.rb:574:in `block (3 levels) in <top (required)>'
     # ./spec/mysql2/client_spec.rb:574:in `block (3 levels) in <top (required)>'

```

[1] https://mariadb.com/kb/en/changes-and-improvements-in-mariadb-connector-c-32/

**Comment by pvalena** [comment]
I forgot to note that we're using mysql2 version 0.5.3 still, and running the tests like this:
```
rspec -Ilib:/builddir/build/BUILDROOT/rubygem-mysql2-0.5.3-10.fc37.x86_64/usr/lib64/gems/ruby/mysql2-0.5.3 -f d spec
```

**Comment by pvalena** [comment]
I see it's fixed already:  https://github.com/brianmario/mysql2/commit/cca57b97ad6d1b1b985376be110b89d2b487dea6
