### ISSUE TITLE
Mac OS update to 12.3 causes a break

### ISSUE THREAD

**Issue by proxlearn** [brianmario/mysql2#1249]
I just upgraded my Mac OS to Monterey version 12.3. Prior to the upgrade, the rails server was running fine. After the upgrade, I am now getting the following error message:

```/Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require': dlopen(/Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 0x0009): Library not loaded: libssl.1.1.dylib (LoadError)
  Referenced from: /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
  Reason: tried: 'libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file), '/Users/pli/ProxLearn/Development/PLIConnectV2/repositories/pli2_tw/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file) - /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<main>'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/bundler.rb:176:in `require'
	from /Users/pli/ProxLearn/Development/PLIConnectV2/repositories/pli2_tw/config/application.rb:19:in `<main>'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/pli/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'```

I tried rebuilding the gem:

`
![image](https://user-images.githubusercontent.com/98374048/159266538-d69ac857-d689-4c5f-ae4f-fde13a581112.png)
`

Same issue.

I tried forcing symlinks:

`ln -s /usr/local/opt/openssl/lib/libssl.1.1.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libcrypto.1.1.dylib /usr/local/lib
`

Same problems. Any ideas?

**Comment by sodabrew** [comment]
Sorry we weren't able to help in a timely manner. Closing this as outdated.
