### ISSUE TITLE
Error when attempting to run `benchmark/active_record.rb`

### ISSUE THREAD

**Issue by richiethomas** [brianmario/mysql2#1269]
I cloned the `mysql2` repo and am currently pointing to commit `e9c662912dc3bd3707e6c7f0c75e591294cffe12`.  I ran `bundle exec ruby benchmark/setup_db.rb` (after adding my DB password and creating the `test` DB directly in MySQL), and the setup script ran successfully.  Now I'm trying to run `bundle exec ruby benchmark/active_record.rb`, but I'm getting the following error:

```
/Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support
/dependencies.rb:332:in `require': Could not load the 'mysql' Active Record adapter. Ensure that the adapter 
is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile. 
(LoadError)
```

I ran into some errors while attempting to install the `mysql` gem (outlined [here](https://stackoverflow.com/questions/72496891/mysql2-gem-how-to-run-benchmark-files)), so I tried replacing the following code:

```
%w[mysql mysql2].each do |adapter|
  TestModel.establish_connection(opts.merge(adapter: adapter))
  ...
end
```

...with the following code:

```
TestModel.establish_connection(opts.merge(adapter: 'mysql2'))
```

However, I then get the following error:

```
/Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support
/dependencies.rb:332:in `require': Error loading the 'mysql2' Active Record adapter. Missing a gem it 
depends on? cannot load such file -- mysql2/mysql2 (LoadError)
```

I traced this 2nd error above to the following file:

```
/Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record
/connection_adapters/abstract/connection_pool.rb:1203
```

It looks like this line of code is trying to require `"active_record/connection_adapters/mysql2_adapter"`.  This file, which I found [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb), then appears to require the `mysql2` gem.  It appears that ActiveRecord errors out when attempting to require the gem, and that this is the root cause for why I can't run the benchmark files.

I'm therefore wondering why this is, i.e. did I miss a step in the setup process somewhere?

**Comment by richiethomas** [comment]
Update- I found the respective `rake` tasks, however I do still see the same `mysql` gem error:

```
~/Desktop/Workspace/OpenSource/mysql2 (master)  $ rake bench:active_record
/Users/richiethomas/.rbenv/versions/2.6.0/bin/ruby benchmark/active_record.rb
Traceback (most recent call last):
	12: from benchmark/active_record.rb:18:in `<main>'
	11: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/benchmark-ips-2.10.0/lib/benchmark/ips.rb:49:in `ips'
	10: from benchmark/active_record.rb:19:in `block in <main>'
	 9: from benchmark/active_record.rb:19:in `each'
	 8: from benchmark/active_record.rb:20:in `block (2 levels) in <main>'
	 7: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_handling.rb:51:in `establish_connection'
	 6: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1046:in `establish_connection'
	 5: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1205:in `resolve_pool_config'
	 4: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
	 3: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	 2: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
	 1: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': cannot load such file -- active_record/connection_adapters/mysql_adapter (LoadError)
	12: from benchmark/active_record.rb:18:in `<main>'
	11: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/benchmark-ips-2.10.0/lib/benchmark/ips.rb:49:in `ips'
	10: from benchmark/active_record.rb:19:in `block in <main>'
	 9: from benchmark/active_record.rb:19:in `each'
	 8: from benchmark/active_record.rb:20:in `block (2 levels) in <main>'
	 7: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_handling.rb:51:in `establish_connection'
	 6: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1046:in `establish_connection'
	 5: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activerecord-6.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1205:in `resolve_pool_config'
	 4: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
	 3: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	 2: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
	 1: from /Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/richiethomas/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': Could not load the 'mysql' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile. (LoadError)
rake aborted!
Command failed with status (1): [/Users/richiethomas/.rbenv/versions/2.6.0/...]
tasks/benchmarks.rake:8:in `block (3 levels) in <top (required)>'
Tasks: TOP => bench:active_record
(See full trace by running task with --trace)
```
