### ISSUE TITLE
Aurora MySQL query ends with `Unknown MySQL error (Mysql2::Error)`, further results out of order

### ISSUE THREAD

**Issue by MmKolodziej** [brianmario/mysql2#1272]
Hi!

I've been debugging weird behavior when running specific queries against one of our Aurora instances. We run multiple of clusters in production, and only one of them seems to be having issues, despite their versions/configurations being almost identical in any aspect that I could think would matter (caching/collations/character sets, etc.)

```ruby
c = ApplicationRecord.connection.raw_connection

c.query('SELECT COUNT(*) FROM advisers').first # Works consistently without backticks
# => [123]
c.query('SELECT COUNT(*) FROM `advisers`').first # Works consistently with backticks
# => [123]

# Works consistently without backticks.
100.times.map { c.query('SELECT COUNT(*) FROM admin_users').first }.uniq 
# => [[40]]

# This never works with backticks
c.query('SELECT COUNT(*) FROM `admin_users`').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)

# Running the working query (no backticks) N times, until I start getting a different error 
# This looks foolish, but this is very repeatable and consistent
c.query('SELECT COUNT(*) FROM admin_users').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)
c.query('SELECT COUNT(*) FROM admin_users').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)
c.query('SELECT COUNT(*) FROM admin_users').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)
c.query('SELECT COUNT(*) FROM admin_users').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)
c.query('SELECT COUNT(*) FROM admin_users').first
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Unknown MySQL error (Mysql2::Error)

# Different error, yet I've changed nothing.
c.query('SELECT COUNT(*) FROM admin_users').first 
# /srv/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query': Mysql2::Error
```
Now that we're getting out of error-zone, let's run something simple 10 times and capture its results.
I'd expect to see either `nil` (connection still failing) or `1` as that's what this is selecting.
```ruby
10.times.map { c.query('SELECT 1 FROM admin_users').first rescue nil }
# => [nil, [40], [40], [40], [40], [40], [1], [1], [1], [1]]
```
But we're getting old results, from queries that supposedly ended in an error (`async: false` in the connection).

Looking at Aurora audit logs, I can confirm that all of the queries sent by Ruby are correct and they run successfully.
Interesting part is that I got 1 segfault while running thousands of these erroneous queries (I was using a jumphost though and couldn't preserve enough lines for it to make sense, and never managed to get another one).
I've tried comparing collations/character sets between different tables that fail/work with backticks, but they all seem the same.

I can run the same set of queries from the MySQL client I link below, and they never fail.
I was almost sure it was a cursed instance of DB server, but other clients seem to work properly.

I'd highly appreciate any tips on how to further debug this thing, as I'm out of ideas, and I can only get it to fail on prod. :upside_down_face: 

- MySQL server version: `5.7.12` (aurora/rds flavored, but hopefully this doesn't matter)
- MySQL client: `mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
- mysql2 version: `0.5.3` (I've looked at `0.5.4` release, haven't found a fix, but I'll try to update regardless)
- Ruby: `3.0.3`

**Comment by MmKolodziej** [comment]
This turned out to probably be an Aurora bug. AWS support suggested clearing cache with `RESET QUERY CACHE;` and the issue was not reproducible afterwards.
