### ISSUE TITLE
This gem was compiled for 10.5.19-MariaDB but the client library is 3.1.20.

### ISSUE THREAD

**Issue by cdelrosario** [brianmario/mysql2#1313]
Spent all day trying to fix this, any help would be greatly appreciated.

### Setup

- OS: MacOS Monterey
- Database: MariaDB 10.5 installed via Homebrew
- Ruby 2.1.18
- Ruby version manager: RbEnv
- Rails 3.2.22.2
- mysql2: 0.3.13

### Background
Previously using MySQL 5.6 uninstalled 5.6 and installed MariaDB@10.5 all via homebrew

Compiling:
```
gem install mysql2 -v '0.3.18' -- -–with-mysql-config=/usr/local/opt/mariadb@10.5/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
```

Result:
```
Building native extensions with: '-–with-mysql-config=/usr/local/opt/mariadb@10.5/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include'
This could take a while...
Successfully installed mysql2-0.3.18
Installing ri documentation for mysql2-0.3.18
1 gem installed
```

then did:
```
bundle install
Bundle complete! 143 Gemfile dependencies, 286 gems now installed.

bundle info mysql2
  * mysql2 (0.3.18)
  Summary: A simple, fast Mysql library for Ruby, binding to libmysql
  Homepage: http://github.com/brianmario/mysql2
  Path: /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/mysql2-0.3.18

 bundle show mysql2
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/mysql2-0.3.18
```

### Problem

When I start rails using `rails s` I get:
```
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'mysql2'. (Bundler::GemRequireError)
Gem Load Error is: Incorrect MySQL client library version! This gem was compiled for 10.5.19-MariaDB but the client library is 3.1.20.
Backtrace for gem load error is:
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
/Users/bobuser/go/src/bitbucket.org/ffxblue/api-legacy-hagrid/config/application.rb:12:in `<top (required)>'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `require'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `block in <top (required)>'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `tap'
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
Bundler Error Backtrace:
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
  from /Users/bobuser/go/src/bitbucket.org/ffxblue/api-legacy-hagrid/config/application.rb:12:in `<top (required)>'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `require'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `block in <top (required)>'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `tap'
  from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

**Comment by sodabrew** [comment]
Could you try mysql2 0.5.5, there have been a number of fixes to improve MariaDB compatibility.

This warning means that mysql2 used the MariaDB client/server headers at compile time but is linked with the MariaDB Connector/C at runtime. There may be subtle differences in definitions that cause misbehavior at runtime, so the code was written to be cautious of this. I consider mysql2 0.3.x to be out of support window (by quite a few years)

**Comment by cdelrosario** [comment]
Thank you for assisting :)

I compiled with:
```
gem install mysql2 -v '0.5.5' -- -–with-mysql-config=/usr/local/opt/mariadb@10.5/bin/mysql_config --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
```

Now get this error: `can't activate mysql2 (~> 0.3.10), already activated mysql2-0.5.5`
```
/Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (can't activate mysql2 (~> 0.3.10), already activated mysql2-0.5.5. Make sure all dependencies are added to Gemfile.) (LoadError)
	from /Users/bobuser/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
```

I also did `gem install activerecord-mysql2-adapter` and then `bundle install` but still get the same error above

**Comment by sodabrew** [comment]
Unfortunately Rails 3.x pins to an earlier version of mysql2 gem. You would need to upgrade Rails to use a newer version, or subscribe to a service that provides updates to very old Rails versions.

Your best bet to get the older version of mysql2 gem working may be to try and align your client libraries, given the blocker to upgrade rails in order to upgrade mysql2.

**Comment by cdelrosario** [comment]
Unfortunately upgrading rails definitely out of the question. I am not really sure where I can get this mysql2 old gem :(

**Comment by cdelrosario** [comment]
Will going back to MySQL 5.6 fix this issue?

**Comment by cdelrosario** [comment]
>  align your client libraries, given the blocker to upgrade rails in order to upgrade mysql2.
How do I go about aligning my client library?

**Comment by rmoestl** [comment]
I stumbled upon this issue because I had a similar issue two week before. @cdelrosario, in terms of upgrading Rails you may consider <https://railslts.com/> by @kratob and Co.

They are also maintaining a mysql2 fork which potentially solves those issues: <https://github.com/makandra/mysql2>. It solved mine.

**Comment by sodabrew** [comment]
Nice, that's great to hear. I see the 0.3.x-lts branch on that fork is pulling in changes from newer mysql2 gems that are bugfixes and support for newer versions of MySQL and MariaDB: https://github.com/makandra/mysql2/commits/0.3.x-lts

Rails LTS is a great thing - developers making their trade supporting older Rails versions while the community focuses its energy on newer versions going forward.

**Comment by sodabrew** [comment]
Resolved by #1406
