### ISSUE TITLE
Mysql2::Client session_track specs fail against MySQL 8.0.33

### ISSUE THREAD

**Issue by yahonda** [brianmario/mysql2#1321]
### Steps to reproduce

```
mysql -uroot
mysql> create database test;
mysql> exit

git clone https://github.com/brianmario/mysql2
cd mysql2
bundle install
bundle exec rake compile
bundle exec rake spec
```

### Expected result:
All of specs should finish successfully

### Actual result:
Mysql2::Client session_track specs fail against MySQL 8.0.33

```ruby
Failures:

  1) Mysql2::Client session_track returns changes system variables for SESSION_TRACK_SYSTEM_VARIABLES
     Failure/Error: expect(res).to eq(%w[session_track_state_change ON])

       expected: ["session_track_state_change", "ON"]
            got: ["session_track_state_change", "ON", "statement_id", "32956"]

       (compared using ==)
     # ./spec/mysql2/client_spec.rb:1086:in `block (3 levels) in <top (required)>'

  2) Mysql2::Client session_track returns multiple session track type values when available
     Failure/Error: expect(res).to eq(%w[session_track_transaction_info CHARACTERISTICS])

       expected: ["session_track_transaction_info", "CHARACTERISTICS"]
            got: ["session_track_transaction_info", "CHARACTERISTICS", "statement_id", "32970"]

       (compared using ==)
     # ./spec/mysql2/client_spec.rb:1099:in `block (3 levels) in <top (required)>'

Finished in 14.85 seconds (files took 0.2044 seconds to load)
338 examples, 2 failures, 7 pending

Failed examples:

rspec ./spec/mysql2/client_spec.rb:1083 # Mysql2::Client session_track returns changes system variables for SESSION_TRACK_SYSTEM_VARIABLES
rspec ./spec/mysql2/client_spec.rb:1095 # Mysql2::Client session_track returns multiple session track type values when available

Randomized with seed 14180
```

### Versions installed
$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

- MySQL 8.0.33
```
$ sudo apt list --installed | grep mysql

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libmysqlclient-dev/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed]
libmysqlclient21/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed,automatic]
mysql-client-8.0/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed,automatic]
mysql-client-core-8.0/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed,automatic]
mysql-common/jammy,now 5.8+1.0.8 all [installed,automatic]
mysql-server-8.0/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed,automatic]
mysql-server-core-8.0/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 amd64 [installed,automatic]
mysql-server/jammy-updates,jammy-security,now 8.0.33-0ubuntu0.22.04.2 all [installed]
$
```

- Ubuntu 22.04
```
$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```

**Comment by yahonda** [comment]
I've not found which change introduce this behavior change, this commit log says like that.

https://github.com/mysql/mysql-server/commit/7f706978815dbcefbfdad3b4ab3690ba7a992fbb

> Since the server reports the statement_id in the session tracker,
