### ISSUE TITLE
LoadError: libruby.so.2.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mavendonovanhubbard** [brianmario/mysql2#1331]
I can bundle install the mysql2 gem just fine, but when I try to require the gem I get the following error.

```
$ bundle exec ruby -e "require 'mysql2'"
Traceback (most recent call last):
        3: from -e:1:in `<main>'
        2: from -e:1:in `require'
        1: from /home/app/current/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<top (required)>'
/home/app/current/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `require': libruby.so.2.7: cannot open shared object file: No such file or directory - /home/app/current/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.so (LoadError)
```

I can see the mysql.so file has been created correctly, but the libruby.so.2.7 file appears to be missing from mysql2.so.
```
$ ldd /home/app/current/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.so
        linux-vdso.so.1 (0x00007ffdd25ea000)
        /usr/lib/x86_64-linux-gnu/libjemalloc.so.2 (0x00007f8695a53000)
        libruby.so.2.7 => not found
        libmysqlclient.so.21 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.21 (0x00007f86952ff000)
        libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f86952dc000)
        libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f86950ea000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8694f9b000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8694db7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8694db1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8694d96000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f8694d03000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f8694a2d000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8694a11000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8695d46000)
```

The libruby.so.2.7 file is present at `/usr/lib/x86_64-linux-gnu/` just like all the other .so files but for some reason it wasn't linked properly.

The machine does have `libmysqlclient-dev` and `libmysqlclient21` installed.

**Comment by mavendonovanhubbard** [comment]
This was caused by compiling mysql2 on one system and then copying it over to a second system where the libruby.so.2.7 was found at a different path.
