### ISSUE TITLE
Cannot find include dir(s) /opt/homebrew/Cellar/mysql/8.0.28_1

### ISSUE THREAD

**Issue by sunil-sharma** [brianmario/mysql2#1344]
On My local mysql installed at this place 
 `/opt/homebrew/opt/mysql@8.0/bin`
 
 But somehow `bundle` command trying to install from `Cannot find include dir(s) /opt/homebrew/Cellar/mysql/8.0.28_1/include:/opt/homebrew/Cellar/mysql/8.0.28_1/include:/opt/homebrew/Cellar/mysql/8.0.28_1/include` path. This folder structure is not present.
 
 My PATH variable looks like this 
 `echo $PATH                                                            
/opt/homebrew/opt/mysql@8.0/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/bin:/Users/sunilsharma/.rvm/gems/ruby-3.0.6@edcast-5.0/bin:/Users/sunilsharma/.rvm/gems/ruby-3.0.6@global/bin:/Users/sunilsharma/.rvm/rubies/ruby-3.0.6/bin:/Users/sunilsharma/.rvm/bin:/Users/sunilsharma/.nvm/versions/node/v6.17.1/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/homebrew/Cellar/mysql/8.2.0_1/bin:/Users/sunilsharma/.rvm/bin:/opt/homebrew/Cellar/mysql/8.2.0_1/bin:/opt/homebrew/Cellar/mysql/8.2.0_1/include:/Users/sunilsharma/.rvm/bin:/opt/homebrew/Cellar/mysql/8.2.0_1/bin:/opt/homebrew/Cellar/mysql/8.2.0_1/include`

And due to above I am getting following error on bundle

`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sunilsharma/.rvm/gems/ruby-3.0.6@edcast-5.0/gems/mysql2-0.5.5/ext/mysql2
/Users/sunilsharma/.rvm/rubies/ruby-3.0.6/bin/ruby -I /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0 -r ./siteconf20240117-37838-w80s7x.rb extconf.rb --with-mysql-lib\=/opt/homebrew/Cellar/mysql/8.0.28_1/lib --with-mysql-dir\=/opt/homebrew/Cellar/mysql/8.0.28_1
--with-mysql-config\=/opt/homebrew/Cellar/mysql/8.0.28_1/bin/mysql_config --with-mysql-include\=/opt/homebrew/Cellar/mysql/8.0.28_1/include
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_gc_mark_movable()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enc_interned_str() in ruby.h... yes
/opt/homebrew/bin/brew
-----
Cannot find include dir(s) /opt/homebrew/Cellar/mysql/8.0.28_1/include:/opt/homebrew/Cellar/mysql/8.0.28_1/include:/opt/homebrew/Cellar/mysql/8.0.28_1/include
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sunilsharma/.rvm/rubies/ruby-3.0.6/bin/$(RUBY_BASE_NAME)
	--with-openssl-dir
	--without-openssl-dir
	--with-mysql-dir
	--with-mysql-include=${mysql-dir}/include
	--with-mysql-lib=${mysql-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/sunilsharma/.rvm/gems/ruby-3.0.6@edcast-5.0/extensions/arm64-darwin-21/3.0.0/mysql2-0.5.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/sunilsharma/.rvm/gems/ruby-3.0.6@edcast-5.0/gems/mysql2-0.5.5 for inspection.
Results logged to /Users/sunilsharma/.rvm/gems/ruby-3.0.6@edcast-5.0/extensions/arm64-darwin-21/3.0.0/mysql2-0.5.5/gem_make.out

  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/rubygems/installer.rb:837:in `build_extensions'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/source/rubygems.rb:204:in `install'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:59:in `block in install_with_settings'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/rubygems_integration.rb:575:in `install_with_build_args'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:59:in `install_with_settings'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/sunilsharma/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing mysql2 (0.5.5), and Bundler cannot continue.

In Gemfile:
  edpay was resolved to 1.0.0, which depends on
    mysql2

`

I couldn't figure out where this path with `8.0.28_1` is present on my machine.

**Comment by sodabrew** [comment]
Sorry we weren't able to help in a timely manner. Closing this as outdated.
