### ISSUE TITLE
[Install][Redmine][Win] An error occurred while installing mysql2 (0.5.6), and Bundler cannot continue.

### ISSUE THREAD

**Issue by gajet5** [brianmario/mysql2#1361]
```
PS C:\redmine> bundle install
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Installing mysql2 0.5.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mysql2-0.5.6/ext/mysql2
C:/Ruby32-x64/bin/ruby.exe extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_gc_mark_movable()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enc_interned_str() in ruby.h... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby32-x64/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --without-openssl-dir
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysql-config
        --without-mysql-config
        --with-mysqlclient-dir
        --without-mysqlclient-dir
        --with-mysqlclient-include
        --without-mysqlclient-include=${mysqlclient-dir}/include
        --with-mysqlclient-lib
        --without-mysqlclient-lib=${mysqlclient-dir}/lib
        --with-mysqlclientlib
        --without-mysqlclientlib
C:/Ruby32-x64/lib/ruby/3.2.0/mkmf.rb:1083:in `block in find_library': undefined
method `split' for nil:NilClass (NoMethodError)

    paths = paths.flat_map {|path| path.split(File::PATH_SEPARATOR)}
                                       ^^^^^^
        from C:/Ruby32-x64/lib/ruby/3.2.0/mkmf.rb:1083:in `each'
        from C:/Ruby32-x64/lib/ruby/3.2.0/mkmf.rb:1083:in `flat_map'
        from C:/Ruby32-x64/lib/ruby/3.2.0/mkmf.rb:1083:in `find_library'
        from extconf.rb:131:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/mysql2-0.5.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mysql2-0.5.6 for inspection.
Results logged to
C:/Ruby32-x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/mysql2-0.5.6/gem_make.out

  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in
build_extensions'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:846:in `build_extensions'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:205:in
`install'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in
`apply_func'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`loop'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`process_queue'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing mysql2 (0.5.6), and Bundler cannot continue.

In Gemfile:
  mysql2
```

**Comment by gajet5** [comment]
This solution:
https://github.com/brianmario/mysql2/issues/1210#issuecomment-965862944
does not work, it leads to an error:
Incorrect MySQL client library version! This gem was compiled for 10.8.8 but the client library is 3.3.8.

**Comment by BraveWhite** [comment]
Have you solved this problem?
I also encountered the same problem

**Comment by gajet5** [comment]
No, I haven't found a solution.
I'm currently dealing with another problem, but this one is still hanging on me. I'm thinking of installing ubuntu and trying to deploy it.

**Comment by simogeo** [comment]
I have the same issue on Ubuntu ! Please see at #1369 

Any update ?

**Comment by gajet5** [comment]
> I have the same issue on Ubuntu ! Please see at #1369
> 
> Any update ?



> I have the same issue on Ubuntu ! Please see at #1369
> 
> Any update ?

Windows, not ubuntu.

**Comment by simogeo** [comment]
Indeed but the problem is similar ... 

By the way, as you can see, I've solved it by modifying the Gemfile to specify the gem mysql2 version, which worked

**Comment by mwdqaqc** [comment]
I have the same problem in windows 10:
After the error for bundle install

Run: bundle exec rake generate_secret_token

c:\redmine-5.1.3>bundle exec rake generate_secret_token
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'mysql2'.
Gem Load Error is: Incorrect MySQL client library version! This gem was compiled for 10.8.8 but the client library is 3.3.8.
Backtrace for gem load error is:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `block in require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:299:in `load_dependency'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.8/lib/active_support/dependencies.rb:332:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2.rb:36:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:60:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:55:in `each'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:55:in `block in require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:44:in `each'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler/runtime.rb:44:in `require'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.15/lib/bundler.rb:212:in `require'
c:/redmine-5.1.3/config/application.rb:18:in `<top (required)>'
c:/redmine-5.1.3/Rakefile:5:in `require'
c:/redmine-5.1.3/Rakefile:5:in `<top (required)>'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:740:in `raw_load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:126:in `block in load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:125:in `load_rakefile'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:82:in `block in run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
C:/Ruby31-x64/bin/rake:33:in `load'
C:/Ruby31-x64/bin/rake:33:in `<main>'
Bundler Error Backtrace:
c:/redmine-5.1.3/config/application.rb:18:in `<top (required)>'
c:/redmine-5.1.3/Rakefile:5:in `require'
c:/redmine-5.1.3/Rakefile:5:in `<top (required)>'

Caused by:
Incorrect MySQL client library version! This gem was compiled for 10.8.8 but the client library is 3.3.8.
c:/redmine-5.1.3/config/application.rb:18:in `<top (required)>'
c:/redmine-5.1.3/Rakefile:5:in `require'
c:/redmine-5.1.3/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by PAWANRAJ-CSE** [comment]
Hi all! Same issue




Check this info:


ruby -v
ruby 3.3.7 (2025-01-15 revision be31f993d7) [x64-mingw-ucrt]

rails -v
Rails 8.0.1

bundle info mysql2
  * mysql2 (0.5.6)
        Summary: A simple, fast Mysql library for Ruby, binding to libmysql
        Homepage: https://github.com/brianmario/mysql2
        Documentation: https://www.rubydoc.info/gems/mysql2/0.5.6
        Source Code: https://github.com/brianmario/mysql2/tree/0.5.6
        Changelog: https://github.com/brianmario/mysql2/releases/tag/0.5.6
        Bug Tracker: https://github.com/brianmario/mysql2/issues
        Path: C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/mysql2-0.5.6


mysql -V
mysql  Ver 8.0.40 for Win64 on x86_64 (MySQL Community Server - GPL)





The error is as follows:







Caused by:
Incorrect MySQL client library version! This gem was compiled for 10.8.8 but the client library is 3.4.3.
<internal:C:/Ruby33-x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:C:/Ruby33-x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
F:/CSE/ROR-2024/PROJECTS/ONE/thirdapp/config/application.rb:7:in `<main>'
F:/CSE/ROR-2024/PROJECTS/ONE/thirdapp/Rakefile:4:in `require_relative'
F:/CSE/ROR-2024/PROJECTS/ONE/thirdapp/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)



How to resolve the issue?? Kindly help

**Comment by simogeo** [comment]
see how I resolved it, here : https://github.com/brianmario/mysql2/issues/1361#issuecomment-2148964432
