### ISSUE TITLE
Unable to migrate on Mysql 8.0.32

### ISSUE THREAD

**Issue by pakozack** [brianmario/mysql2#1380]
Hi guys, I'm trying to deploy my application on production server but when I execute migration I have the following error:

```shell
RAILS_ENV=production bundle exec rake db:migrate
``` 

```shell
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown system variable 'innodb_file_format' (ActiveRecord::StatementInvalid)
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:98:in `block (2 levels) in raw_execute'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1004:in `block in with_raw_connection'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activesupport-7.2.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:976:in `with_raw_connection'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:96:in `block in raw_execute'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activesupport-7.2.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1119:in `log'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:95:in `raw_execute'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:237:in `execute_and_free'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql2/database_statements.rb:18:in `internal_exec_query'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `query'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:106:in `query_value'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql/schema_statements.rb:153:in `default_row_format'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/mysql/schema_statements.rb:86:in `create_table'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/schema_migration.rb:55:in `block in create_table'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:395:in `with_connection'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/schema_migration.rb:53:in `create_table'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/migration.rb:1434:in `initialize'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/migration.rb:1264:in `new'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/migration.rb:1264:in `up'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/migration.rb:1239:in `migrate'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/tasks/database_tasks.rb:251:in `migrate'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/activerecord-7.2.1.1/lib/active_record/railties/databases.rake:93:in `block (2 levels) in <main>'
/var/www/lgcmc-web/shared/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
/home/ubuntu/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
``` 
In my app use ruby 3.2.0, rails 7.2.1.1 and gem mysql2 v 0.5.6. Mysql version is 8.0.32.

Any idea?

**Comment by pakozack** [comment]
Sorry, solved

**Comment by pakozack** [comment]
Solved with 
https://www.reddit.com/r/rails/comments/keam79/rails_mysql_server_on_azure_unknown_system/

I use ProxySQL that report wrong mysql server version.
