### ISSUE TITLE
"Library not loaded" errors on OS X

### ISSUE THREAD

**Issue by keo** [brianmario/mysql2#205]
Every time a new version of mysql2 comes out, I get the following error after installing the new gem:

``` bash
pry(main)> require 'mysql2'
LoadError: dlopen(/Users/keo/.rvm/gems/ruby-1.9.2-p136/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle, 9): Library not loaded: libmysqlclient.18.dylib
  Referenced from: /Users/keo/.rvm/gems/ruby-1.9.2-p136/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle
  Reason: image not found - /Users/keo/.rvm/gems/ruby-1.9.2-p136/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle
from /Users/keo/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
```

I can solve this by running:

``` bash
sudo install_name_tool -change libmysqlclient.18.dylib /usr/local/mysql/lib/libmysqlclient.18.dylib /Users/keo/.rvm/gems/ruby-1.9.2-p136/gems/mysql2-0.3.7/lib/mysql2/mysql2.bundle
```

This is really cumbersome as I have to do this everytime I install mysql2 in a new gemset or upgrade it in the current gemset.

I have this problem on OS X Snow Leopard (10.6) and OS X Lion (10.7), with MySQL binaries from mysql.com

Is there a way we could prevent this?

**Comment by yasserhussain1110** [comment]
@tommyp That worked! 🎉

**Comment by timriley** [comment]
Hi folks, I'm not 100% sure this is a fully solved problem, or perhaps it has somehow become _unsolved_ over the passage of time.

Here's why:

I have mysql 5.7.29 installed via the asdf versioning too. It's installed into `~/.asdf/installs/mysql/5.7.29`.

asdf ensures that `mysql_config` reports the appropriate values for this install dir, e.g.

```
$ mysql_config
Usage: /Users/tim/.asdf/installs/mysql/5.7.29/bin/mysql_config [OPTIONS]
Compiler: Clang 10.0.1
Options:
        --cflags         [-I/Users/tim/.asdf/installs/mysql/5.7.29/include ]
        --cxxflags       [-I/Users/tim/.asdf/installs/mysql/5.7.29/include ]
        --include        [-I/Users/tim/.asdf/installs/mysql/5.7.29/include]
        --libs           [-L/Users/tim/.asdf/installs/mysql/5.7.29/lib -lmysqlclient ]
        --libs_r         [-L/Users/tim/.asdf/installs/mysql/5.7.29/lib -lmysqlclient ]
        --plugindir      [/Users/tim/.asdf/installs/mysql/5.7.29/lib/plugin]
        --socket         [/tmp/mysql.sock]
        --port           [0]
        --version        [5.7.29]
        --libmysqld-libs [-L/Users/tim/.asdf/installs/mysql/5.7.29/lib -lmysqld ]
        --variable=VAR   VAR is one of:
                pkgincludedir [/Users/tim/.asdf/installs/mysql/5.7.29/include]
                pkglibdir     [/Users/tim/.asdf/installs/mysql/5.7.29/lib]
                plugindir     [/Users/tim/.asdf/installs/mysql/5.7.29/lib/plugin]
```

With this in place, I can run `gem install mysql2 -v 0.5.3` and this succeeds. So far so good.

However, when I try to `require "mysql2"`, I see this error:

```
require "mysql2"

LoadError: dlopen(/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 9): Library not loaded: /usr/local/mysql/lib/libmysqlclient.20.dylib
  Referenced from: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
  Reason: image not found - /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle
from /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Caused by LoadError: cannot load such file -- mysql2
from /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

It's trying to load `libmysqlclient.20.dylib` from `/usr/local/lib`, but that dylib does _not_ exist there since I have mysql installed into `~/.asdf/installs/mysql/5.7.29`, which is where the dylib _actually_ resides.

If I use `otool -l` to view the loader instructions inside `mysql2.bundle`, I see the following (output snipped for clarity):

```
otool -l /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle

# ...

Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /Users/tim/.asdf/installs/ruby/2.6.2/lib/libruby.2.6.dylib (offset 24)
   time stamp 2 Thu Jan  1 10:00:02 1970
      current version 2.6.2
compatibility version 2.6.0

Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /usr/local/mysql/lib/libmysqlclient.20.dylib (offset 24)
   time stamp 2 Thu Jan  1 10:00:02 1970
      current version 20.0.0
compatibility version 20.0.0

Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 10:00:02 1970
      current version 1281.0.0
compatibility version 1.0.0

Load command 13
          cmd LC_RPATH
      cmdsize 56
         path /Users/tim/.asdf/installs/mysql/5.7.29/lib (offset 12)
```

See there how in `Load command 11` it's explicitly trying to load `/usr/local/mysql/lib/libmysqlclient.20.dylib`? That's the reason for the error!

If this was truly an issue related to `DYLD_LIBRARY_PATH` config (which AFAICT is ignored these days, anyway, with macOS’ _System Integrity Protection_ in place), then shouldn't that `LC_LOAD_DYLIB` name actually be something like `@rpath/libmysqlclient.20.dylib`? The fact that it has the full path hard-coded would suggest that it wouldn't ever be looking for that file on a list of available paths anyway, right?

At this point my options are to:

1. Symlink the actual dylib from the asdf install into `/usr/local/lib` (which feels wrong)
2. Go into the installed gem's dir and run `install_name_tool -change /usr/local/mysql/lib/libmysqlclient.20.dylib ~/.asdf/installs/mysql/5.7.29/lib/libmysqlclient.20.dylib mysql2.bundle` (which also feels unnecessary)

Both of these options _will_ fix the issue, but I wonder: is there a way as part of the native extension build process for this gem that we can fix this properly?

In case it helps, below is the output of `gem pristine mysql2 -V`, which shows that the `rpath` of `/Users/tim/.asdf/installs/mysql/5.7.29/lib` is properly detected, which is what ultimately leads me to think there is still a bug of some kind in this gem's build process.

Thank you for your time here! 🙇 And if you'd rather I brought this up as a new issue, I'd be happy to do so, please let me know.

```
$ gem pristine mysql2 -V
Restoring gems to pristine condition...
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/CHANGELOG.md
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/LICENSE
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/README.md
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/client.c
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/client.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/extconf.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/infile.c
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/infile.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/mysql2_ext.c
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/mysql2_ext.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/mysql_enc_name_to_ruby.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/mysql_enc_to_ruby.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/result.c
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/result.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/statement.c
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/statement.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2/wait_for_single_fd.h
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/console.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/em.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/error.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/field.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/result.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/statement.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/lib/mysql2/version.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/support/5072E1F5.asc
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/support/libmysql.def
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/support/mysql_enc_to_ruby.rb
/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/support/ruby_enc_to_mysql.rb
Building native extensions. This could take a while...
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
["/Users/tim/.asdf/installs/ruby/2.6.2/bin/ruby", "-I", "/Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0", "-r", "./siteconf20200408-70608-7gak5f.rb", "extconf.rb"]
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
-----
Using mysql_config at /Users/tim/.asdf/shims/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for SSL_MODE_DISABLED in mysql.h... yes
checking for SSL_MODE_PREFERRED in mysql.h... yes
checking for SSL_MODE_REQUIRED in mysql.h... yes
checking for SSL_MODE_VERIFY_CA in mysql.h... yes
checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes
checking for SERVER_QUERY_NO_GOOD_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_NO_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_WAS_SLOW in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_ON in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_OFF in mysql.h... yes
checking for my_bool in mysql.h... yes
-----
Setting rpath to /Users/tim/.asdf/installs/mysql/5.7.29/lib
-----
creating Makefile
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
"make \"DESTDIR=\" clean"
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
"make \"DESTDIR=\""
compiling client.c
compiling infile.c
compiling mysql2_ext.c
compiling result.c
compiling statement.c
linking shared-object mysql2/mysql2.bundle
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
"make \"DESTDIR=\" install"
/usr/local/bin/ginstall -c -m 0755 mysql2.bundle ./.gem.20200408-70608-k2z12c/mysql2
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
/Users/tim/.asdf/installs/ruby/2.6.2/bin/ruby -I /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/2.6.0 -r ./siteconf20200408-70608-7gak5f.rb extconf.rb
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
make "DESTDIR=" clean
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
make "DESTDIR="
current directory: /Users/tim/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mysql2-0.5.3/ext/mysql2
make "DESTDIR=" install
Restored mysql2-0.5.3
```

**Comment by timriley** [comment]
Some extra info, I've edited the `Makefile` inside the gem's `ext/` dir and made this change (i.e. added the `-t -v` options):

```
# LIBS = $(LIBRUBYARG_SHARED) -L/Users/tim/.asdf/installs/mysql/5.7.29/lib -lmysqlclient
LIBS = $(LIBRUBYARG_SHARED) -L/Users/tim/.asdf/installs/mysql/5.7.29/lib -lmysqlclient -t -v
```

The `-t` option seemed useful because of the `ld` man page's description of it:

>      -t          Logs each file (object, archive, or dylib) the linker loads.
>                  Useful for debugging problems with search paths where the
>                  wrong library is loaded.

Then when I run `make "DESTDIR=" clean install` inside that dir, I see this output:

```
compiling client.c
compiling infile.c
compiling mysql2_ext.c
compiling result.c
compiling statement.c
linking shared-object mysql2/mysql2.bundle
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -bundle -dynamic -macosx_version_min 10.15.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -t -o mysql2.bundle -L. -L/Users/tim/.asdf/installs/ruby/2.6.2/lib -L. -L/Users/tim/.asdf/installs/ruby/2.6.2/lib -L/usr/local/lib -L/Users/tim/.asdf/installs/ruby/2.6.2/lib -L/Users/tim/.asdf/installs/mysql/5.7.29/lib client.o infile.o mysql2_ext.o result.o statement.o -rpath /Users/tim/.asdf/installs/mysql/5.7.29/lib -undefined dynamic_lookup -multiply_defined suppress -lruby.2.6 -lmysqlclient -L/usr/local/lib -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
client.o
infile.o
mysql2_ext.o
result.o
statement.o
/Users/tim/.asdf/installs/ruby/2.6.2/lib/libruby.2.6.dylib
/Users/tim/.asdf/installs/mysql/5.7.29/lib/libmysqlclient.dylib
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcache.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcommonCrypto.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcompiler_rt.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcopyfile.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libcorecrypto.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libdispatch.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libdyld.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libkeymgr.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/liblaunch.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libmacho.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libquarantine.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libremovefile.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_asl.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_blocks.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_c.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_configuration.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_coreservices.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_darwin.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_dnssd.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_featureflags.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_info.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_kernel.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_m.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_malloc.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_networkextension.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_notify.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_platform.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_pthread.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_sandbox.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_secinit.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_symptoms.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libsystem_trace.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libunwind.tbd
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/system/libxpc.tbd
/usr/local/bin/ginstall -c -m 0755 mysql2.bundle ./.gem.20200408-70608-k2z12c/mysql2
```

You'll see here that it actually _does_ pick up `/Users/tim/.asdf/installs/mysql/5.7.29/lib/libmysqlclient.dylib` (i.e. the right file)!

So what perplexes me, then, is why when I run `otool -l` over that bundle file (as I shared in my previous comment), it ends up showing `/usr/local/mysql/lib/libmysqlclient.20.dylib` instead...

At this point I'm operating well outside of the bounds of my working knowledge (I'm not a C person) so I would really appreciate any extra help or insight into this problem.

Once again, thank you! 🙇

**Comment by jimbreen** [comment]
@timriley did you ever get any traction on this in some other channel? I'm having the exact same problem with mysql 5.7.31 installed via asdf, albeit with much older versions of ruby and mysql2(legacy codebase). 
```
9): Library not loaded: /usr/local/mysql/lib/libmysqlclient.20.dylib (LoadError)
```

I've tried many different permutations of the `--with-mysql-*`  configuration options without luck. Using `--with-mysql-dir` instead of `--with-mysql-config` did result in there being no reference to `/usr/local/mysql/lib/libmysqlclient.20.dylib` in the otool output, but there wasn't a reference to the correct libmysqlclient path either, and `require 'mysql2'` then resulted in a Symbol not found error.
```
dyld: lazy symbol binding failed: Symbol not found: _mysql_get_client_info
```

I'm wondering if there are any less unsavory "fixes" than than the two workarounds you identified.

**Comment by nomasprime** [comment]
I'm having the same issue as @timriley and @jimbreen.

Did anyone solve this?

@tenderlove given above, do you still consider this issue closed?
