### ISSUE TITLE
Cannot install on ruby 2.0.0p0 (2013-02-24) [i386-mingw32]

### ISSUE THREAD

**Issue by DHB** [brianmario/mysql2#359]
``` sh
$ gem install mysql2 -- '--with-mysql-lib="h:\database\MySQL\MySQL%20Server%205.5\lib" --with-mysql-include="h:\database\MySQL\MySQL%20Serv
er%205.5\include"'
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-mysql-lib="h:\database\MySQL\MySQL%20Server%205.5\lib" --with-mysql-include="h:\database\MySQL\MySQ
L%20Server%205.5\include"'
This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.
```

gcc (rubenvb-4.7.2-release) 4.7.2

Gists containing gem_make.out and mkmf.log is here:  https://gist.github.com/DHB/5067144

Confusing enough, “bundle install” seemingly installed the gem - without yielding any errors.
However, Rake afterwards barked:

``` sh
$ rake -T --trace
rake aborted!
cannot load such file -- mysql2/2.0/mysql2
h:/Ruby200_p0/lib/ruby/gems/2.0.0/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2/mysql2.rb:2:in `require'
h:/Ruby200_p0/lib/ruby/gems/2.0.0/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
h:/Ruby200_p0/lib/ruby/gems/2.0.0/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2.rb:9:in `require'
h:/Ruby200_p0/lib/ruby/gems/2.0.0/gems/mysql2-0.3.11-x86-mingw32/lib/mysql2.rb:9:in `<top (required)>'
```

mysql2.rb contains:

``` ruby
RUBY_VERSION =~ /(\d+.\d+)/
require "mysql2/#{$1}/mysql2"
```

but $1 directory 2.0 does not exist.

**Comment by sodabrew** [comment]
I released mysql2 version 0.3.18 **with windows binaries** today!

If you find a problem with the 0.3.18 version, please open a new ticket.

I am locking this issue now.
