### ISSUE TITLE
Installing to MySQL from XAMPP on Mac

### ISSUE THREAD

**Issue by bengalamx** [brianmario/mysql2#556]
Hi, i have installed XAMPP and i want RoR to work with the Mysql Library previously installed, so i am trying to do `gem install mysql2`, with no success at all; i have tried with a lot of variations:

> sudo gem install mysql2 -- ..

> --with-mysql-dir=Applications/XAMPP/xamppfiles/mysql/
> --with-mysql-include=Applications/XAMPP/xamppfiles/include/mysql/
> --with-mysql-lib=Applications/XAMPP/xamppfiles/lib/mysql
> --with-mysql-config=Applications/XAMPP/xamppfiles/bin/mysql

But every time i get the next error:

```
Building native extensions with: 'OPTIONS'
This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --with-mysql-config=Applications/XAMPP/xamppfiles/bin/mysql
checking for ruby/thread.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:502:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from extconf.rb:9:in `<main>'


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.16 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/mysql2-0.3.16/ext/mysql2/gem_make.out
```

Here are all the MySQL paths on XAMPP:

> Applications/XAMPP/xamppfiles/bin/mysql

![captura de pantalla 2014-11-04 18 29 02 2](https://cloud.githubusercontent.com/assets/3253845/4910701/da698438-6482-11e4-8f7f-bb46e245ced8.png)

> Applications/XAMPP/xamppfiles/lib/mysql/

![captura de pantalla 2014-11-04 18 29 10](https://cloud.githubusercontent.com/assets/3253845/4910702/dec0b68c-6482-11e4-9616-0da1bdb6c7b0.png)

> Applications/XAMPP/include/mysql

![captura de pantalla 2014-11-04 18 30 14](https://cloud.githubusercontent.com/assets/3253845/4910707/ec4ce046-6482-11e4-928a-dd3c8741a6de.png)

Can i get any help?

Regards.

**Comment by ekyfauzi** [comment]
Hi, i have same issue too,
Can you resolve?
Please share,

Thanks,

**Comment by sodabrew** [comment]
@ekyfauzi Please describe the issue you see, there are several problems in this thread so you will need to explain.

**Comment by ekyfauzi** [comment]
Hi @sodabrew 
I have same problem with @bengalamx 

I run gem install was successful with:
```
sudo gem install mysql2 -- --with-mysql-config="/Applications/XAMPP/xamppfiles/bin/" --with-mysql-include="/Applications/XAMPP/xamppfiles/include/" --with-mysql-lib="/Applications/XAMPP/xamppfiles/lib/mysql/"
```

When i run `bundle` and then `rails s`, i get this:
```
dyld: lazy symbol binding failed: Symbol not found: _mysql_get_client_info
  Referenced from: /Users/ekyfauzi/.rvm/gems/ruby-2.1.2@global/extensions/x86_64-darwin-14/2.1.0/mysql2-0.3.17/mysql2/mysql2.bundle
  Expected in: flat namespace

dyld: Symbol not found: _mysql_get_client_info
  Referenced from: /Users/ekyfauzi/.rvm/gems/ruby-2.1.2@global/extensions/x86_64-darwin-14/2.1.0/mysql2-0.3.17/mysql2/mysql2.bundle
  Expected in: flat namespace
```

Hope somebody can help me

**Comment by sodabrew** [comment]
You are mis-over-configuring your build. Use only one of `with-mysql-config` or `with-mysql-dir`. In the case of `with-mysql-config`, supply the complete path including the mysql_config binary, not just the bin dir.

I advise against `sudo gem install` - if your application is using Bundler, then `bundle install` is the correct way to build the gems for your application.

If you need to pass options into the mysql2 gem build as part of bundler, it is documented here: 
http://bundler.io/v1.3/man/bundle-config.1.html#BUILD-OPTIONS

For example:
```
bundle config build.mysql2  --with-mysql-config=/Applications/XAMPP/xamppfiles/bin/mysql_config
```

**Comment by 7900ms** [comment]
Having XAMPP on mac installed, this is what I did:
```
> ln -s /Applications/XAMPP/xamppfiles/lib/libmariadb.3.dylib /usr/local/lib/libmariadb.3.dylib 
```
in Gemfile:
```
source 'https://rubygems.org'
gem 'mysql2' 
```
run cmd:
```
> bundle config build.mysql2 --with-mysql-dir="/Applications/XAMPP/xamppfiles"
> bundle install
# OR > bundle install --clean --no-cache --path vendor/bundle 
> bundle exec ruby 1.rb 
```
inside 1.rb
```
#!/usr/bin/ruby
# -*- coding: UTF-8 -*-
require 'mysql2'
client = Mysql2::Client.new(
    :host     => 'localhost',
    :username => 'root',
    :password => 'root',
    :database => 'pdb1',
    :encoding => 'utf8'
    )
results = client.query("SELECT * FROM `people` ORDER BY `date` DESC ")
results.each do |row|
  puts " #{row['name']} - #{row['age']} - #{row['height']} -- #{row['date']}"
end
```

**Comment by bitsnaps** [comment]
@7900ms  nice trick, but I didn't work for me, the missing part is headers source of mysql from xampp-devel.
https://stackoverflow.com/questions/16657304/mysql-h-is-missing-ruby-on-rails-osx/64542750#64542750
