### ISSUE TITLE
Failed to build gem native extension on Ubuntu 14.04, MariaDB 10.1, rbenv

### ISSUE THREAD

**Issue by vicovictor** [brianmario/mysql2#564]
While trying to run bundle install for `mysql2 (= 0.3.13)`, I got the following. I am using Ruby 1.9.3-p551.

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /home/deployer/.rbenv/versions/1.9.3-p551/bin/ruby extconf.rb 
checking for rb_thread_blocking_region()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/deployer/.rbenv/versions/1.9.3-p551/bin/ruby
/home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:894:in `block in have_func'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:893:in `have_func'
    from extconf.rb:9:in `<main>'


Gem files will remain installed in /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/mysql2-0.3.13 for inspection.
Results logged to /home/deployer/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/mysql2-0.3.13/ext/mysql2/gem_make.out
An error occurred while installing mysql2 (0.3.13), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.13'` succeeds before bundling.
```

**Comment by straightdave** [comment]
@simi 's answer i workable to me.

**Comment by vhosakot** [comment]
`yum install gcc gcc-c++ ruby-devel` resolved this error in CentOS for me.
