### ISSUE TITLE
Segmentation fault [Windows 7 - 64 bits, Ruby 2.1.5]

### ISSUE THREAD

**Issue by Javix** [brianmario/mysql2#573]
Sorry for a possible duplication of https://github.com/brianmario/mysql2/issues/567. But I still have the described error `Segmentation fault`. 
Reproduced on:
- MS Windows 7 Enterprise, 64 bits
- ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]
- mysql2 version 0.3.17.

I created manually the vendor folder in mysql2 gem folder:
```
C:\Ruby21-x64\lib\ruby\gems\2.1.0\gems\mysql2-0.3.17\vendor
```
and copy-pasted the `libmysql.dll` from `C:\Program Files\MySQL\MySQL Connector C 6.1\lib`.
I also cpy-pasted the same `libmysql.dll` into Ruby bin folder:
```
C:\Ruby21-x64\bin
```
When running the example code:
```
require 'active_record'
require 'mysql2'

client = Mysql2::Client.new(
	:database => "draft",
	:host => "localhost",
	:username => "root")
```
I got the error:
```
C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/mysql2-0.3.17/mysql2/mysql2.so: [BUG] Segmentat
ion fault
ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0009 p:-7321722 s:0040 e:000039 TOP    [FINISH]
c:0008 p:---- s:0038 e:000037 CFUNC  :require
c:0007 p:0115 s:0034 e:000033 METHOD C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0083 s:0024 e:000023 TOP    C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2.rb:8 [FIN
ISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :require
c:0004 p:0073 s:0018 e:000017 RESCUE C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135
c:0003 p:0444 s:0015 e:000014 METHOD C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144
c:0002 p:0015 s:0005 E:0024e0 EVAL   mysql_connection.rb:2 [FINISH]
c:0001 p:0000 s:0002 E:0014e8 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
mysql_connection.rb:2:in `<main>'
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17/lib/mysql2.rb:8:in `<top (required)>'
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0xa) [0x00000000779412FA]
C:\Windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x9c) [0x000007FEFDA710DC]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_bugreport+0xa4) [0x000000006B417364]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_name_err_mesg_new+0x841) [0x000000006B2C9801]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_bug+0x45) [0x000000006B2CA545]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_check_safe_str+0x351) [0x000000006B398E11]
 [0x0000000000401A85]
C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x9c) [0x00000000779085C8]
C:\Windows\SYSTEM32\ntdll.dll(RtlDecodePointer+0xad) [0x0000000077919D2D]
C:\Windows\SYSTEM32\ntdll.dll(RtlUnwindEx+0xbbf) [0x00000000779091CF]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x0000000077941248]
C:\Ruby21-x64\lib\ruby\gems\2.1.0\extensions\x64-mingw32\2.1.0\mysql2-0.3.17\mysql2\mysql2.so(Init_mysql2+0x1f
78) [0x00000000006F6308]
 [0x00000000006F343D]
C:\Ruby21-x64\lib\ruby\gems\2.1.0\extensions\x64-mingw32\2.1.0\mysql2-0.3.17\mysql2\mysql2.so(Init_mysql2+0x5a
) [0x00000000006F43EA]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(dln_load+0x1d6) [0x000000006B281646]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_call_cfunc+0x130) [0x000000006B414300]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_require_safe+0x56f) [0x000000006B2D558F]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_error_arity+0x1c6) [0x000000006B402206]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x1618) [0x000000006B406C98]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x5a8d) [0x000000006B40B10D]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_iseq_eval+0x183) [0x000000006B413C23]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_rubylevel_errinfo+0x66c) [0x000000006B2D396C]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_require_safe+0x5a9) [0x000000006B2D55C9]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_error_arity+0x1c6) [0x000000006B402206]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_f_send+0x5c1) [0x000000006B411601]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x1618) [0x000000006B406C98]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x5a8d) [0x000000006B40B10D]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_iseq_eval_main+0x1d0) [0x000000006B413E40]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_check_copyable+0x304a) [0x000000006B2CF31A]
C:\Ruby21-x64\bin\x64-msvcrt-ruby210.dll(ruby_run_node+0x51) [0x000000006B2D2231]
 [0x0000000000402D14]
 [0x00000000004013D7]
 [0x00000000004014F8]
C:\Windows\system32\kernel32.dll(BaseThreadInitThunk+0xd) [0x00000000777E59ED]
```
If you need more detailed stack trace, I put it in the following gist:
https://gist.github.com/Javix/5b36883ba61487763c84

**Comment by sodabrew** [comment]
Please try mysql2 master, since #473 has been merged.

**Comment by Javix** [comment]
I had to download the gem and install it locally because enterprise proxy restrictions. Is there a way to pick up the master version ? (I've never installed it like that:), just from the terminal). Thank you

**Comment by betam4x** [comment]
Working for me.  Any idea on a final release date?

**Comment by Ebiggs01** [comment]
@sodabrew Also running into this/blocked. Any update on the release date or instructions on how to install the fix in the interim?

**Comment by betam4x** [comment]
@Ebiggs01 if using in rails:

put this in your gemfile:  gem 'mysql2', github: 'brianmario/mysql2'

at a terminal, type bundle config build.mysql2 --with-mysql-dir=C:\path\to\mysql-connector 

after running that command run a bundle install and you should be in good shape.

**Comment by Javix** [comment]
@betam4x: as I told previously, I know how to pick up the latest gem version either from master or from a specific branch by putting it in the Gemfile. The problem is that in this case it will not work for me because of proxy & firewall restrictions (yeah, there are still companies that work like that :). So the only solution twas to download the gem from ruby gems.org and install it locally:
```
gem instal mysql2 -l
```

**Comment by Javix** [comment]
It does not work either even I point it to git/master as follows in a simple Gemfile:
```
gem 'mysql2', git: 'git://github.com/brianmario/mysql2.git'
```
and run `bundle install`. Here is the stack trace:
```
d:\>bundle
DL is deprecated, please use Fiddle
Fetching git://github.com/brianmario/mysql2.git
Resolving dependencies...

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby21/bin/ruby.exe extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
```
options as usual, - I omitted to be shorter.
When tried to run with options from a Windows command prompt:
```
d:\>gem install mysql2 -- --with-mysql-dir="C:/Program Files/MySQL/MySQL Connector J"
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-mysql-dir=C:/Program Files/MySQL/MySQL Connector J'
This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    C:/Ruby21/bin/ruby.exe extconf.rb --with-mysql-dir=C:/Program Files/MySQL/MySQL Connector J
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Cannot find include dir(s) C:/Program/include
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby21/bin/ruby
        --with-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby21/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17 for inspection.
Results logged to C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/mysql2-0.3.17/gem_make.out
```
it failed again.

**Comment by sodabrew** [comment]
Are you actually using `Connector/J`? You need `Connector/C`.

**Comment by araho** [comment]
im facing the same issue too on windows 8.1 
i downloaded the zip file from brianmario/mysql2

i Run this in cmd
```
 C:/Ruby21-x64/bin/ruby.exe extconf.rb --with-mysql-dir=C:\mysql2-master
```
this is what i got 

```
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Cannot find include dir(s) C:\mysql2-master/include
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby21-x64/bin/ruby
        --with-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/mysql2-0.3.17 for inspection.
Results logged to C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/mysql2-0.3.17/gem_make.out
```

**Comment by sodabrew** [comment]
Does this directory exist? `C:\mysql2-master/include`

**Comment by araho** [comment]
emm no it doesn't exist http://screencast.com/t/YAnSsuYDFB

**Comment by Javix** [comment]
Oups, retried with the correct path to Connector C:
```
c:\Users\XXXX\Documents\Soft\gems>gem install mysql2 -l -- --with-mysql-dir="C:/Program Files/MySQL/MySQL
Connector C 6.1"
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-mysql-dir=C:/Program Files/MySQL/MySQL Connector C 6.1'
This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    C:/Ruby21-x64/bin/ruby.exe extconf.rb --with-mysql-dir=C:/Program Files/MySQL/MySQL Connector C 6.1
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Cannot find include dir(s) C:/Program/include
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby21-x64/bin/ruby
        --with-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib

extconf failed, exit code 1
```

**Comment by sodabrew** [comment]
This is resolved by the 0.3.18 release.

**Comment by betam4x** [comment]
Just wanted to say thanks to the developers for making this happen!

**Comment by sodabrew** [comment]
You're welcome! It was an interesting challenge.
