### ISSUE TITLE
Tests fail with MySQL 5.5 on OSX

### ISSUE THREAD

**Issue by tamird** [brianmario/mysql2#633]
Below output is with 1.9.3 but the same error happens with 2.2.2 and rbx-2.5.5 as well.

```
$ git clean -dxf && PATH=$(brew --prefix mysql55)/bin:$PATH bundle exec rake
Removing Gemfile.lock
Removing lib/mysql2/mysql2.bundle
Removing spec/configuration.yml
Removing spec/my.cnf
Removing tmp/
mkdir -p tmp/x86_64-darwin14.3.0/mysql2/1.9.3
cd tmp/x86_64-darwin14.3.0/mysql2/1.9.3
/Users/tamird/.rubies/ruby-1.9.3-p547/bin/ruby -I. ../../../../ext/mysql2/extconf.rb
checking for ruby/thread.h... no
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using mysql_config at /usr/local/opt/mysql55/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Setting rpath to /usr/local/opt/mysql55/lib
-----
creating Makefile
cd -
cd tmp/x86_64-darwin14.3.0/mysql2/1.9.3
make
compiling ../../../../ext/mysql2/client.c
compiling ../../../../ext/mysql2/infile.c
compiling ../../../../ext/mysql2/mysql2_ext.c
compiling ../../../../ext/mysql2/result.c
compiling ../../../../ext/mysql2/statement.c
linking shared-object mysql2/mysql2.bundle
cd -
mkdir -p tmp/x86_64-darwin14.3.0/stage/lib/mysql2
cp LICENSE tmp/x86_64-darwin14.3.0/stage/LICENSE
cp README.md tmp/x86_64-darwin14.3.0/stage/README.md
mkdir -p tmp/x86_64-darwin14.3.0/stage/examples
cp examples/eventmachine.rb tmp/x86_64-darwin14.3.0/stage/examples/eventmachine.rb
cp examples/threaded.rb tmp/x86_64-darwin14.3.0/stage/examples/threaded.rb
mkdir -p tmp/x86_64-darwin14.3.0/stage/ext/mysql2
cp ext/mysql2/client.c tmp/x86_64-darwin14.3.0/stage/ext/mysql2/client.c
cp ext/mysql2/client.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/client.h
cp ext/mysql2/extconf.rb tmp/x86_64-darwin14.3.0/stage/ext/mysql2/extconf.rb
cp ext/mysql2/infile.c tmp/x86_64-darwin14.3.0/stage/ext/mysql2/infile.c
cp ext/mysql2/infile.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/infile.h
cp ext/mysql2/mysql2_ext.c tmp/x86_64-darwin14.3.0/stage/ext/mysql2/mysql2_ext.c
cp ext/mysql2/mysql2_ext.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/mysql2_ext.h
cp ext/mysql2/mysql_enc_name_to_ruby.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/mysql_enc_name_to_ruby.h
cp ext/mysql2/mysql_enc_to_ruby.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/mysql_enc_to_ruby.h
cp ext/mysql2/result.c tmp/x86_64-darwin14.3.0/stage/ext/mysql2/result.c
cp ext/mysql2/result.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/result.h
cp ext/mysql2/statement.c tmp/x86_64-darwin14.3.0/stage/ext/mysql2/statement.c
cp ext/mysql2/statement.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/statement.h
cp ext/mysql2/wait_for_single_fd.h tmp/x86_64-darwin14.3.0/stage/ext/mysql2/wait_for_single_fd.h
cp lib/mysql2.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2.rb
cp lib/mysql2/client.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/client.rb
cp lib/mysql2/console.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/console.rb
cp lib/mysql2/em.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/em.rb
cp lib/mysql2/error.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/error.rb
cp lib/mysql2/field.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/field.rb
cp lib/mysql2/result.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/result.rb
cp lib/mysql2/statement.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/statement.rb
cp lib/mysql2/version.rb tmp/x86_64-darwin14.3.0/stage/lib/mysql2/version.rb
mkdir -p tmp/x86_64-darwin14.3.0/stage/spec
cp spec/configuration.yml.example tmp/x86_64-darwin14.3.0/stage/spec/configuration.yml.example
mkdir -p tmp/x86_64-darwin14.3.0/stage/spec/em
cp spec/em/em_spec.rb tmp/x86_64-darwin14.3.0/stage/spec/em/em_spec.rb
cp spec/my.cnf.example tmp/x86_64-darwin14.3.0/stage/spec/my.cnf.example
mkdir -p tmp/x86_64-darwin14.3.0/stage/spec/mysql2
cp spec/mysql2/client_spec.rb tmp/x86_64-darwin14.3.0/stage/spec/mysql2/client_spec.rb
cp spec/mysql2/error_spec.rb tmp/x86_64-darwin14.3.0/stage/spec/mysql2/error_spec.rb
cp spec/mysql2/result_spec.rb tmp/x86_64-darwin14.3.0/stage/spec/mysql2/result_spec.rb
cp spec/mysql2/statement_spec.rb tmp/x86_64-darwin14.3.0/stage/spec/mysql2/statement_spec.rb
cp spec/rcov.opts tmp/x86_64-darwin14.3.0/stage/spec/rcov.opts
cp spec/spec_helper.rb tmp/x86_64-darwin14.3.0/stage/spec/spec_helper.rb
cp spec/test_data tmp/x86_64-darwin14.3.0/stage/spec/test_data
mkdir -p tmp/x86_64-darwin14.3.0/stage/support
cp support/libmysql.def tmp/x86_64-darwin14.3.0/stage/support/libmysql.def
cp support/mysql_enc_to_ruby.rb tmp/x86_64-darwin14.3.0/stage/support/mysql_enc_to_ruby.rb
cp support/ruby_enc_to_mysql.rb tmp/x86_64-darwin14.3.0/stage/support/ruby_enc_to_mysql.rb
install -c tmp/x86_64-darwin14.3.0/mysql2/1.9.3/mysql2.bundle lib/mysql2/mysql2.bundle
cp tmp/x86_64-darwin14.3.0/mysql2/1.9.3/mysql2.bundle tmp/x86_64-darwin14.3.0/stage/lib/mysql2/mysql2.bundle
/Users/tamird/.rubies/ruby-1.9.3-p547/bin/ruby -I/Users/tamird/.gem/ruby/1.9.3/gems/rspec-core-3.2.3/lib:/Users/tamird/.gem/ruby/1.9.3/gems/rspec-support-3.2.2/lib /Users/tamird/.gem/ruby/1.9.3/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 6578

Mysql2::Statement
  should tell us the result count
  should raise an exception without a block
  should keep its result after other query
  should create a statement
  should let us iterate over results
  should tell us about the fields
  should let us execute our statement
  should tell us the field count
  should tell us the param count
  should select dates
  should raise an exception when server disconnects
  row data type mapping
    should return TrueClass or FalseClass for a TINYINT value if :cast_booleans is enabled
    should return Fixnum for a MEDIUMINT value
    should return TrueClass or FalseClass for a BIT(1) value if :cast_booleans is enabled
    should return String for a SET value
    should return a String for LONGBLOB
    should return a String for TEXT
    should return Fixnum for a YEAR value
    should return Time when timestamp is < 1901-12-13 20:45:52
    should return Fixnum for a SMALLINT value
    should return Fixnum for an INT value
    should return a String for TINYBLOB
    should return Fixnum for a BIGINT value
    should return Float for a DOUBLE value
    should return a String for VARCHAR
    should return Date for a DATE value
    should return a String for CHAR
    should return String for an ENUM value
    should return BigDecimal for a DECIMAL value
    should return Time when timestamp is > 2038-01-19T03:14:07
    should return Float for a FLOAT value
    should return Fixnum for a TINYINT value
    should return nil for a NULL value
    should raise an error given an invalid DATETIME
    should return String for a BIT(1) value
    should return Time for a TIME value
    should return a String for VARBINARY
    should return Time for a TIMESTAMP value when within the supported range
    should return String for a BINARY value
    should return String for a BIT(64) value
    should return Time for a DATETIME value when within the supported range
    should return a String for TINYTEXT
    should return a String for MEDIUMBLOB
    should return a String for LONGTEXT
    should return a String for MEDIUMTEXT
    should return a String for BLOB
    string encoding for LONGTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for TINYTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for TINYBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for TEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for SET values
      should use Encoding.default_internal
      should default to the connection's encoding if Encoding.default_internal is nil
    string encoding for BLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for MEDIUMTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for VARBINARY values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for LONGBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for CHAR values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for VARCHAR values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for MEDIUMBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for ENUM values
      should use Encoding.default_internal
      should default to the connection's encoding if Encoding.default_internal is nil
    string encoding for BINARY values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
  #fields
    should return an array of field names in proper order
    method should exist
  streaming result
    should be able to stream query result
  utf8_db
    should be able to retrieve utf8 param query correctly
    should be able to retrieve utf8 field names correctly
    should be able to retrieve query with param in different encoding correctly
  #each
    should yield the same value for #first if streaming is disabled
    should yield rows as hash's
    should yield rows as hash's with symbol keys if :symbolize_keys was set to true
    should throw an exception if we try to iterate twice when streaming is enabled
    should be able to return results as an array
    should cache previously yielded results by default
    should yield different value for #first if streaming

Mysql2::Result
  should be able to return the number of rows in the result set
  should raise a TypeError exception when it doesn't wrap a result set
  should respond to #count, which is aliased as #size
  should respond to #each
  should have included Enumerable
  should raise a Mysql2::Error exception upon a bad query
  row data type mapping
    should return Fixnum for a TINYINT value
    should return Fixnum for a SMALLINT value
    should return TrueClass or FalseClass for a TINYINT value if :cast_booleans is enabled
    should raise an error given an invalid DATETIME
    should return a String for MEDIUMTEXT
    should return a String for BLOB
    should return Fixnum for a BIGINT value
    should return Time for a DATETIME value when within the supported range
    should return TrueClass or FalseClass for a BIT(1) value if :cast_booleans is enabled
    should return Fixnum for a MEDIUMINT value
    should return a String for VARBINARY
    should return Fixnum for an INT value
    should return Float for a FLOAT value
    should return a String for CHAR
    should return Time for a TIME value
    should return String for a BINARY value
    should return Date for a DATE value
    should return Fixnum for a YEAR value
    should return Time when timestamp is < 1901-12-13 20:45:52
    should return BigDecimal for a DECIMAL value
    should return String for a BIT(1) value
    should return nil values for NULL and strings for everything else when :cast is false
    should return String for an ENUM value
    should return String for a BIT(64) value
    should return a String for LONGTEXT
    should return a String for LONGBLOB
    should return Time when timestamp is > 2038-01-19T03:14:07
    should return a String for TINYBLOB
    should return a String for TEXT
    should return Float for a DOUBLE value
    should return a String for VARCHAR
    should return a String for TINYTEXT
    should return a String for MEDIUMBLOB
    should return nil for a NULL value
    should return Time for a TIMESTAMP value when within the supported range
    should return String for a SET value
    string encoding for LONGTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for TINYTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for TINYBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for TEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for SET values
      should use Encoding.default_internal
      should default to the connection's encoding if Encoding.default_internal is nil
    string encoding for BLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for MEDIUMTEXT values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for VARBINARY values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for LONGBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for CHAR values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for VARCHAR values
      should use Encoding.default_internal
      should default to utf-8 if Encoding.default_internal is nil
    string encoding for MEDIUMBLOB values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
    string encoding for ENUM values
      should use Encoding.default_internal
      should default to the connection's encoding if Encoding.default_internal is nil
    string encoding for BINARY values
      should not use Encoding.default_internal
      should default to binary if Encoding.default_internal is nil
  streaming
    should raise an exception if streaming ended due to a timeout
    #count should be zero for rows after streaming when there were no results
    should retain the count when mixing first and each
    should maintain a count while streaming
    should not yield nil at the end of streaming
  #each
    should yield different value for #first if streaming
    should throw an exception if we try to iterate twice when streaming is enabled
    should yield the same value for #first if streaming is disabled
    should be able to return results as an array
    should yield rows as hash's with symbol keys if :symbolize_keys was set to true
    should cache previously yielded results by default
    should not cache previously yielded results if cache_rows is disabled
    should yield rows as hash's
  metadata queries
    should show tables
  #fields
    should return an array of field names in proper order
    method should exist

Mysql2::Client
  should default flags to (REMEMBER_OPTIONS, LONG_PASSWORD, LONG_FLAG, TRANSACTIONS, PROTOCOL_41, SECURE_CONNECTION)
  should have a global default_query_options hash
  should execute init command
  should respond to #escape
  should respond to #encoding
  #thread_id should be a Fixnum
  should not close connections when running in a child process
  should respond to #warning_count
  should send init_command after reconnect
  should be able to connect via SSL options (PENDING: DON'T WORRY, THIS TEST PASSES - but SSL is not enabled in your MySQL daemon.)
  #server_info should require an open connection
  should not leave dangling connections after garbage collection
  should be able to close properly
  should respond to #server_info
  should expect write_timeout to be a positive integer
  #info should return a hash containing the client version ID and String
  should respond to #socket
  should be able to connect to database with numeric-only name
  should respond to #query_info
  should respond to #close
  should accept connect flags and pass them to #connect
  should raise an exception upon connection failure
  should respond to escape
  should not raise an exception on create for a valid encoding
  should expect read_timeout to be a positive integer
  #server_info should return a hash containing the client version ID and String
  should expect connect_timeout to be a positive integer
  should raise a Mysql2::Error exception upon connection failure
  should respond to #ping
  should respond to #info
  should raise an exception on create for invalid encodings
  should respond to #query
  #thread_id should return a boolean
  should respond to #thread_id
  #escape
    should require an open connection
    should not overflow the process stack
    should return the passed string if nothing was escaped
    should return a new SQL-escape version of the passed string
    should not overflow the thread stack
  escape
    should carry over the original string's encoding
    should not overflow the process stack
    should return the passed string if nothing was escaped
    should return a new SQL-escape version of the passed string
    should not overflow the thread stack
  strings returned by .info
    should be tagged as ascii
  using defaults file
    should not raise an exception without default group
    should not raise an exception for valid defaults group
  strings returned by #info
    should be tagged as ascii
  write operations api
    #last_id should handle BIGINT auto-increment ids above 32 bits
    #last_id should return a Fixnum, the from the last INSERT/UPDATE
    #last_id should return a Fixnum, the from the last INSERT/UPDATE
    should respond to #last_id
    should respond to #last_id
  #query
    #socket should return a Fixnum (file descriptor from C)
    should return results as a hash by default
    should require an open connection
    should be able to return results as an array
    should be able to return results with symbolized keys
    #socket should require an open connection
    should describe the thread holding the active query
    should be impervious to connection-corrupting timeouts (PENDING: `Thread.handle_interrupt` is not defined)
    should not retain query options set on a query for subsequent queries, but should retain it in the result
    should only accept strings as the query parameter
    should timeout if we wait longer than :read_timeout
    should not let you query again if iterating is not finished when streaming
    should run signal handlers while waiting for a response
    should not allow another query to be sent without fetching a result first
    should let you query again if iterating is finished when streaming
    threaded queries should be supported
    should allow changing query options for subsequent queries
    evented async queries should be supported
    Multiple results sets
      #more_results? should work
      should raise an exception when one of multiple statements fails
      returns multiple result sets
      #more_results? should work with stored procedures
      does not interfere with other statements
      will raise on query if there are outstanding results to read
      #abandon_results! should work
    when a non-standard exception class is raised
      should handle Timeouts without leaving the connection hanging if reconnect is true (FAILED - 1)
      should close the connection when an exception is raised
      should handle Timeouts without leaving the connection hanging if reconnect is set to true after construction true (FAILED - 2)
  select_db
    should switch databases
    should return the database switched to
    should raise a Mysql2::Error when the database doesn't exist
    should respond to #select_db
  #query_info
    when has some info
      should retrieve it
    when no info present
      should 0
  :local_infile
    should raise an error when a non-existent file is loaded
    should raise an error when local_infile is disabled
    should LOAD DATA LOCAL INFILE
  strings returned by #server_info
    should use Encoding.default_internal
    should default to the connection's encoding if Encoding.default_internal is nil
  #warning_count
    when has a warnings
      should > 0
    when no warnings
      should 0

Mysql2::EM::Client
  should support queries in callbacks
  should not raise error when closing client with no query running
  should not swallow exceptions raised in callbacks
  should support async queries
  when an exception is raised by the client
    should fail the deferrable
    should swallow exceptions raised in by the client

Mysql2::Error
  responds to error_number and sql_state, with aliases
  encoding
    returns sql state as ASCII
    returns error messages as UTF-8 by default
    returns error messages and sql state in Encoding.default_internal if set

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Mysql2::Client should be able to connect via SSL options
     # DON'T WORRY, THIS TEST PASSES - but SSL is not enabled in your MySQL daemon.
     Failure/Error: expect(results[0]['Value']).not_to be_empty
       expected `"".empty?` to return false, got true
     # ./spec/mysql2/client_spec.rb:141:in `block (2 levels) in <top (required)>'

  2) Mysql2::Client#query should be impervious to connection-corrupting timeouts
     # `Thread.handle_interrupt` is not defined
     Failure/Error: expect { @client.query('SELECT 1') }.to_not raise_error
       expected no Exception, got #<Mysql2::Error: closed MySQL connection> with backtrace:
         # ./lib/mysql2/client.rb:85:in `_query'
         # ./lib/mysql2/client.rb:85:in `query'
         # ./spec/mysql2/client_spec.rb:471:in `block (4 levels) in <top (required)>'
         # ./spec/mysql2/client_spec.rb:471:in `block (3 levels) in <top (required)>'
     # ./spec/mysql2/client_spec.rb:471:in `block (3 levels) in <top (required)>'

Failures:

  1) Mysql2::Client#query when a non-standard exception class is raised should handle Timeouts without leaving the connection hanging if reconnect is true
     Failure/Error: expect { client.query('SELECT 1') }.to_not raise_error
       expected no Exception, got #<Mysql2::Error: Lost connection to MySQL server during query> with backtrace:
         # ./lib/mysql2/client.rb:85:in `_query'
         # ./lib/mysql2/client.rb:85:in `query'
         # ./spec/mysql2/client_spec.rb:484:in `block (5 levels) in <top (required)>'
         # ./spec/mysql2/client_spec.rb:484:in `block (4 levels) in <top (required)>'
     # ./spec/mysql2/client_spec.rb:484:in `block (4 levels) in <top (required)>'

  2) Mysql2::Client#query when a non-standard exception class is raised should handle Timeouts without leaving the connection hanging if reconnect is set to true after construction true
     Failure/Error: expect { Timeout.timeout(0.1, ArgumentError) { client.query('SELECT SLEEP(1)') } }.to raise_error(ArgumentError)
       expected ArgumentError, got #<Mysql2::Error: Lost connection to MySQL server during query> with backtrace:
         # ./lib/mysql2/client.rb:85:in `_query'
         # ./lib/mysql2/client.rb:85:in `query'
         # ./spec/mysql2/client_spec.rb:495:in `block (6 levels) in <top (required)>'
         # ./spec/mysql2/client_spec.rb:495:in `block (5 levels) in <top (required)>'
         # ./spec/mysql2/client_spec.rb:495:in `block (4 levels) in <top (required)>'
     # ./spec/mysql2/client_spec.rb:495:in `block (4 levels) in <top (required)>'

Finished in 6.77 seconds (files took 0.1676 seconds to load)
277 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/mysql2/client_spec.rb:480 # Mysql2::Client#query when a non-standard exception class is raised should handle Timeouts without leaving the connection hanging if reconnect is true
rspec ./spec/mysql2/client_spec.rb:487 # Mysql2::Client#query when a non-standard exception class is raised should handle Timeouts without leaving the connection hanging if reconnect is set to true after construction true

Randomized with seed 6578

/Users/tamird/.rubies/ruby-1.9.3-p547/bin/ruby -I/Users/tamird/.gem/ruby/1.9.3/gems/rspec-core-3.2.3/lib:/Users/tamird/.gem/ruby/1.9.3/gems/rspec-support-3.2.2/lib /Users/tamird/.gem/ruby/1.9.3/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by sodabrew** [comment]
Oh, for you too. So it's not just me! :)

**Comment by tamird** [comment]
Yeah, what's weird is that travis runs mysql 5.5.

I'll open a PR to add an osx+5.5 travis build and see what happens.

**Comment by sodabrew** [comment]
Closing, since at least it's documented now with the pending test.
