### ISSUE TITLE
Mysql2::Error encoding failing in a strange way on OS X

### ISSUE THREAD

**Issue by sodabrew** [brianmario/mysql2#641]
I've seen this failure intermittently on Travis for OS X builds:

```
  1) Mysql2::Error encoding returns error messages and sql state in Encoding.default_internal if set
     Failure/Error: client.query(valid_utf8)
     LoadError:
       dlopen(e, 9): image not found - e
     # ./lib/mysql2/error.rb:26:in `encode'
     # ./lib/mysql2/error.rb:26:in `sql_state='
     # ./lib/mysql2/client.rb:80:in `_query'
     # ./lib/mysql2/client.rb:80:in `block in query'
     # ./lib/mysql2/client.rb:79:in `handle_interrupt'
     # ./lib/mysql2/client.rb:79:in `query'
     # ./spec/mysql2/error_spec.rb:31:in `block (3 levels) in <top (required)>'
     # ./spec/mysql2/error_spec.rb:76:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:19:in `with_internal_encoding'
     # ./spec/mysql2/error_spec.rb:75:in `block (3 levels) in <top (required)>'
```

**Comment by sodabrew** [comment]
Closing, I haven't seen this error occur again in a long time.
