### ISSUE TITLE
Date / Time tests are failing on Ruby 2.1 on Windows

### ISSUE THREAD

**Issue by sodabrew** [brianmario/mysql2#732]
Seen on AppVeyor: https://ci.appveyor.com/project/sodabrew/mysql2/build/399 only for Ruby 2.1, both 32-bit and 64-bit, interestingly.

```
  1) Mysql2::Result row data type mapping should return DateTime when timestamp is < 1901-12-13 20:45:52
     Failure/Error: expect(r.first['test']).to be_an_instance_of(klass)
       expected 1901-12-13 20:45:51.000000000 +0000 to be an instance of DateTime
     # ./spec/mysql2/result_spec.rb:295:in `block (3 levels) in <top (required)>'
 
  2) Mysql2::Result row data type mapping should return DateTime when timestamp is > 2038-01-19T03:14:07
     Failure/Error: expect(r.first['test']).to be_an_instance_of(klass)
       expected 2038-01-19 03:14:08.000000000 +0000 to be an instance of DateTime
     # ./spec/mysql2/result_spec.rb:301:in `block (3 levels) in <top (required)>'
 
  3) Mysql2::Statement row data type mapping should return DateTime when timestamp is > 2038-01-19T03:14:07
     Failure/Error: expect(r.first['test']).to be_an_instance_of(klass)
       expected 2038-01-19 03:14:08.000000000 +0000 to be an instance of DateTime
     # ./spec/mysql2/statement_spec.rb:397:in `block (3 levels) in <top (required)>'
 
  4) Mysql2::Statement row data type mapping should return DateTime when timestamp is < 1901-12-13 20:45:52
     Failure/Error: expect(r.first['test']).to be_an_instance_of(klass)
       expected 1901-12-13 20:45:51.000000000 +0000 to be an instance of DateTime
     # ./spec/mysql2/statement_spec.rb:391:in `block (3 levels) in <top (required)>'
 
Finished in 13.52 seconds (files took 0.25002 seconds to load)
```

**Comment by sodabrew** [comment]
This seems to be resolved more recently.
