### ISSUE TITLE
reconnect doesnt work for SSL connections

### ISSUE THREAD

**Issue by waelchatila** [brianmario/mysql2#740]
steps to reproduce:

1) client.rb is using the following:

@query_options={:as=>:hash, :async=>false, :cast_booleans=>true, :symbolize_keys=>true, :database_timezone=>:utc, :application_timezone=>nil, :cache_rows=>true, :connect_flags=>2147525125, :cast=>true, :default_file=>nil, :default_group=>nil, :host=>”HOST", :database=>”DB", :username=>”USERNAME", :password=>”PASSWORD", :pool=>"50", :sslkey=>”/path/to/key.pem", :sslcert=>”/path/to/cert.pem", :sslca=>”/path/to/ca-cert.pem", :sslcapath=>”/path/to", :sslcipher=>"DHE-RSA-AES256-SHA", :sslverify=>false, :reconnect=>true}, options={}}

issue some command with your client

2) login to mysql cli and do 

select CONCAT('KILL ', id, ';') from information_schema.processlist where DB='YOUR DB';

and then copy-past the kill commands

3) re-issue a command with your client

exception: 
2016-03-02 18:22:52.636 [ERROR] (pid:3302) – [852e9c31d649b8b5e13d3a08f4058755] EXCEPTION CAUGHT: Access denied for user ‘XYZ’@'XYZ' (using password: NO)
        /.../bundle/ruby/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
        /.../bundle/ruby/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
        /.../bundle/ruby/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
        /.../bundle/ruby/2.1.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:144:in `block in method_missing'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:131:in `with'
        /.../bundle/ruby/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:143:in `method_missing'

**Comment by sodabrew** [comment]
Closing as stale -- no reply in 9 years, and the architecture this would depend on has moved on since gem 0.4.3.

mysql2 never tears down and rebuilds the underlying `MYSQL*` handle across a reconnect -- `mysql_options()` calls for SSL (`ssl_mode`, `sslkey`/`sslcert`/`sslca`, etc.) are set once on that same handle before the initial connect, and libmysqlclient's own `MYSQL_OPT_RECONNECT` machinery reuses that handle rather than replacing it. SSL options set that way persist across a reconnect by construction; there's no separate connect path that would need to re-apply them. If this still reproduces on a current gem version, please reopen with a fresh repro.
