### ISSUE TITLE
Lost connection to MySQL server at 'waiting for initial communication packet', system error: 10060

### ISSUE THREAD

**Issue by Punknoodles** [brianmario/mysql2#814]
C:/Ruby23/lib/ruby/gems/2.3.0/gems/mysql2-0.4.5-x86-mingw32/lib/mysql2/client.rb:89:in `connect': Lost connection to MySQL server at 'waiting for initial communication packet', system error: 10060 (Mysql2::Error)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mysql2-0.4.5-x86-mingw32/lib/mysql2/client.rb:89:in `initialize'

**Comment by Punknoodles** [comment]
I really am bad at this. :P had it pointing to the wrong port.
