### ISSUE TITLE
Millisecond precision "Incorrect datetime value"

### ISSUE THREAD

**Issue by mahemoff** [brianmario/mysql2#833]
I've been getting an error with timestamps defined as `datetime(3)`:

> ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect datetime value: '2017-03-16T11:13:10.906000000+0000.906000' for column 'updated_at' at row 1: UPDATE `posts` SET `locale_ids` = '[746783232,0,874050868]', `updated_at` = '2017-03-16T11:13:10.906000000+0000.906000' WHERE `posts`.`id` = 1055918169

It appends the fractional part of the time value (`.906000`) to the timezone so it appears twice in the same string. I only see it in development and weirdly, it usually works fine after restarting Rails (but then fails a while later).

Tried with mysql2 gem v0.4.5 on MySQL 5.7.17. (Not sure if related to the database, but I think was previously working with same config on MariaDB 10 and MySQL 5.5.)

**Comment by sodabrew** [comment]
Are you calling `DateTime#to_s` on the variable you are setting for `updated_at` in your AR query?
 AR expects that you would pass the native object, and it will convert it to a format appropriate for the column.

You mention it works at first and then begins to fail later, do you have have `reconnect: true` in your database.yml? I wonder if there is a database connection session setting that isn't being set on reconnect, and so after a few hours/days, when you're using a reconnected-connection, the settings are different.

**Comment by mahemoff** [comment]
I'm not calling `DateTime#to_s` explicitly. AFAICT this is just regular ActiveRecord code running, e.g. using `update_attributes`, `touch`, etc - stack trace below. Maybe it's a third-party gem but not aware of any that would cause it.

```
[23] pry(main)> begin ; Post.last.touch; rescue => ex ; puts ex, ex.backtrace; end
[DEBUG 2017-03-16 14:29:17 +0000 /opt/proj/environments/development.rb:78]   Post Load (0.6ms)  SELECT  `posts`.* FROM `posts` ORDER BY `posts`.`id` DESC LIMIT 1
[DEBUG 2017-03-16 14:29:17 +0000 /opt/proj/environments/development.rb:78]     1 row, 1.59 KB
[DEBUG 2017-03-16 14:29:17 +0000 /opt/proj/environments/development.rb:78]    (0.2ms)  BEGIN
[DEBUG 2017-03-16 14:29:17 +0000 /opt/proj/environments/development.rb:78]   SQL (0.5ms)  UPDATE `posts` SET `posts`.`updated_at` = '2017-03-16T14:29:17.832000000+0000.832000' WHERE `posts`.`id` = 1003105890
[DEBUG 2017-03-16 14:29:17 +0000 /opt/proj/environments/development.rb:78]    (0.2ms)  ROLLBACK
Mysql2::Error: Incorrect datetime value: '2017-03-16T14:29:17.832000000+0000.832000' for column 'updated_at' at row 1: UPDATE `posts` SET `posts`.`updated_at` = '2017-03-16T14:29:17.832000000+0000.832000' WHERE `posts`.`id` = 1003105890
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:48:in `exec_delete'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `update'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:395:in `update_all'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/persistence.rb:512:in `touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/callbacks.rb:292:in `block in touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_touch_callbacks'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/callbacks.rb:292:in `touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:328:in `block in touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/transactions.rb:328:in `touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/touch_later.rb:37:in `touch'
/home/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.2/lib/active_record/no_touching.rb:53:in `touch'
```

I do have `reconnect: true`. That could very well explain why this works on starting and then fails at some point later until I restart the server. I don't know why the reconnection would change behaviour like that.

**Comment by sodabrew** [comment]
If you are issuing a query that sets session variables, you should put that query in the `init_command` option: https://github.com/brianmario/mysql2#initial-command-on-connect-and-reconnect

**Comment by mahemoff** [comment]
I don't think I'm issuing any command to set session variables. my.cnf has `sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREA
TE_USER,NO_ENGINE_SUBSTITUTION"` (which was around when the error showed up, but that's also when I upgraded from Maria 10 to MySQL 5.7).  There's nothing dynamically changing session variables in the code that I know of.

**Comment by sodabrew** [comment]
I was just thinking about, what version of Ruby and of Rails are you using?

**Comment by sodabrew** [comment]
Just coming back to check on old tickets, were you able to sort this out? Do you still need assistance on it?

**Comment by mahemoff** [comment]
Hi, actually I think I can close this. I found the issue was probably related to a workaround mentioned here:  http://stackoverflow.com/questions/16800939/activerecord-milliseconds-arent-taken-into-account-when-using-a-where-clause which reconfigures Time::DATE_FORMATS[:db].

I haven't seen the issue since removing that, so I'll close this. Thanks for your help.
