### ISSUE TITLE
Unable to `gem install mysql2 -v '0.4.5` - Ubuntu 16.04, Ruby 2.4 - but 2.3.1 works

### ISSUE THREAD

**Issue by Pistos** [brianmario/mysql2#835]
```
% gem install mysql2 -v '0.4.5'
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2:
        ERROR: Failed to build gem native extension.

    current directory: /home/pistos/.rvm/gems/ruby-2.4.0@smash-api-2/gems/mysql2-0.4.5/ext/mysql2
/home/pistos/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170318-1586-11itd0u.rb extconf.rb
checking for rb_absint_size()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/pistos/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
/home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file.
 (RuntimeError)
You have to install development tools first.
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:768:in `try_func'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:1055:in `block in have_func'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from /home/pistos/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:1054:in `have_func'
        from extconf.rb:26:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/pistos/.rvm/gems/ruby-2.4.0@smash-api-2/extensions/x86_64-linux/2.4.0/mysql2-0.4.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/pistos/.rvm/gems/ruby-2.4.0@smash-api-2/gems/mysql2-0.4.5 for inspection.
Results logged to /home/pistos/.rvm/gems/ruby-2.4.0@smash-api-2/extensions/x86_64-linux/2.4.0/mysql2-0.4.5/gem_make.out
```

The `mkmf.log` file has:

```
" -o conftest -I/home/pistos/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/x86_64-linux -I/home/pistos/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0/ruby/backward -I/home/pistos/.rvm/rubies/ruby-2.4.0/include/ruby-2.4.0 -I.    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized  -fPIC conftest.c  -L. -L/home/pistos/.rvm/rubies/ruby-2.4.0/lib -Wl,-R/home/pistos/.rvm/rubies/ruby-2.4.0/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-R'/../lib' -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
sh: 1: -o: not found
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

You'll note that the beginning of the command in double quotes is just ` -o ...`, which looks like the actual command/program (`ld`?  `gcc`?) is missing from the command line.

I believe I have all the necessary Ubuntu packages installed, because the gem installs error-free with Ruby 2.3.1.

```
 % mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
```

**Comment by sodabrew** [comment]
Your installation of Ruby 2.4.0 appears to have a misconfigured RbConfig. Could you post the output from `ruby -r pp -e 'pp RbConfig::CONFIG.select { |k,v| k =~ /^C/ }'` that may shed light on the situation.

**Comment by Pistos** [comment]
Thanks for looking into this.  Here's the output of that:

```
{"CONFIGURE"=>"configure",
 "COMMON_HEADERS"=>"",
 "COMMON_MACROS"=>"",
 "COMMON_LIBS"=>"",
 "CROSS_COMPILING"=>"no",
 "CCDLFLAGS"=>"-fPIC",
 "CHDIR"=>"cd -P",
 "CP"=>"cp",
 "CC_VERSION_MESSAGE"=>
  "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609\n" +
  "Copyright (C) 2015 Free Software Foundation, Inc.\n" +
  "This is free software; see the source for copying conditions.  There is NO\n" +
  "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.",
 "CC_VERSION"=>" --version",
 "CSRCFLAG"=>"",
 "COUTFLAG"=>"-o ",
 "CPPOUTFILE"=>"-o conftest.i",
 "CPP"=>" -E",
 "CXXFLAGS"=>
  "-O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized",
 "CPPFLAGS"=>"  ",
 "CFLAGS"=>
  "-O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized  -fPIC",
 "CXX"=>"g++",
 "CC"=>""}
```

**Comment by sodabrew** [comment]
The CC version output tells me you do have the GCC compiler installed and working, and clearly you were able to compile Ruby. But this is where the problem is:

```
"CC"=>""}
```

The value should be `gcc` so that Ruby extensions are able to compile themselves as well!

I'm not sure how that ended up blank, and so I'm at a loss for recommendations on how to resolve it, but I hope this provides a useful clue to continue searching.

**Comment by sodabrew** [comment]
Ping - is this problem still occurring for you?

**Comment by majormoses** [comment]
I tried to reproduce this in a docker container and on my workstation but am no longer able to. Either something was fixed here or within the release of ruby 2.4.1 which was released days after this was reported.

**Comment by sodabrew** [comment]
I am certain the problem was specific to your container build. There were no recent Ruby 2.4 compatibility changes to the gem. At any rate, may we close this issue?

**Comment by Pistos** [comment]
Please hold for at least a day or two.  I will check the scenario again with 2.4.1 on that system, but I do not have luxury to do so immediately.

**Comment by sodabrew** [comment]
Any luck confirming that this is resolved in your local container?

**Comment by Pistos** [comment]
I am able to install without issue using Ruby 2.4.1.  Thank you for attention; I shall close this issue now.
