### ISSUE TITLE
Problemy using gem and MySQL 5.0.95.

### ISSUE THREAD

**Issue by mastro83** [brianmario/mysql2#844]
Hello,

I'm tryed varius mysql2 gem version but I got always this error, can someone help me? :(

mysql2 0.4.6.
Db is Mysql 5.0.95

'Malformed packet'
Extracted source (around line #70):
connect user, pass, host, port, database, socket, flags

```
Mysql2::Error (Malformed packet):
  mysql2 (0.4.6) lib/mysql2/client.rb:89:in `connect'
  mysql2 (0.4.6) lib/mysql2/client.rb:89:in `initialize'
  activerecord (4.2.8) lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
  activerecord (4.2.8) lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /Users/michele/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /Users/michele/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.8) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.8) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.8) lib/active_record/migration.rb:383:in `connection'
  activerecord (4.2.8) lib/active_record/migration.rb:370:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.8) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.8) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.6) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.6) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.6) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.6) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  rack (1.6.6) lib/rack/lock.rb:17:in `call'
  rack (1.6.6) lib/rack/content_length.rb:15:in `call'
  rack (1.6.6) lib/rack/handler/webrick.rb:88:in `service'
  /Users/michele/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/michele/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/michele/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
database.yml:
default: &default
  adapter: mysql2
  pool: 25
  timeout: 5000

development:
  <<: *default
  host: 192.168.2.50
  database: asteriskcdrdb
  username: root
  password: pwd1234
  port: 3306
  flags:
    - PROTOCOL_41

**Comment by sodabrew** [comment]
mysql2 gem version 0.2 is far out of date, and if you're using Rails 4.x and Ruby 2.x, you'll be well-served by updating to the latest mysql2 gem 0.4.x

**Comment by sodabrew** [comment]
The `malformed packet` error usually means you have a mis-matched setting for the "old protocol" flag. Have you changed the `flags` setting in your database.yml recently? You may have removed the `PROTOCOL_41` flag value that needs to be there.

Using a newer mysql2 gem, you'll have access to better ways to set your flags values:
https://github.com/brianmario/mysql2#flags-option-parsing

**Comment by mastro83** [comment]
Hello, I'm using mysql2 0.4.6.
Db is Mysql 5.0.95
added your suggest flag:

  flags:
    - PROTOCOL_41

Same problem, can you help me?

Thanks

**Comment by sodabrew** [comment]
Do you know what client library version you're using? I wonder if your client library is much newer while your server version is much older?

**Comment by mastro83** [comment]
How to know client library? I use mac os 10.11

**Comment by sodabrew** [comment]
What's your output from `otool -L <gem path ...>/lib/mysql2/mysql2.bundle`?

On my system, for example, my client library is installed from MacPorts, and it's MySQL 5.7 / library version 20:
```
$ otool -L mysql2-sodabrew/lib/mysql2/mysql2.bundle
mysql2-sodabrew/lib/mysql2/mysql2.bundle:
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/local/lib/mysql57/mysql/libmysqlclient.20.dylib (compatibility version 20.0.0, current version 20.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by sodabrew** [comment]
Ping - is this problem still occurring for you?

**Comment by sodabrew** [comment]
Closing due to lack of updates.

**Comment by kimpastro** [comment]
Is this problem solved? Having issues with that.
