### ISSUE TITLE
mysql2/client.rb:70:in `connect': SSL connection error: protocol version mismatch (Mysql2::Error)

### ISSUE THREAD

**Issue by Chrisgo-75** [brianmario/mysql2#862]
I have an older Rails application that was running nicely on Ubuntu 14.04 LTS until Server Administrator upgraded to Ubuntu 16.04 LTS. Any ideas as to what is causing the SSL protocol mismatch error?
Thank you,
Chris

__Current Versions Being Used__
Ruby 2.1.6
Rails 3.2.21
mysql2 gem -v 0.3.21
Replaced libmysqlclient18 with libmysqlclient20.

__In trying to get this application to spin up, I get the below error__
```
$ rails s
=> Booting WEBrick
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/usr/local/rvm/gems/ruby-2.1.6@eops/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect': SSL connection error: protocol version mismatch (Mysql2::Error)
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
	from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
	from /usr/local/rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:310:in `clear_cache!'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activerecord-3.2.21/lib/active_record/railtie.rb:103:in `block (2 levels) in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:418:in `_run__1836245211465360502__prepare__2076197971389641643__callbacks'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/cgarndt/ror_dev/uw_live_projects/git_repo/eops/application/config/environment.rb:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/cgarndt/ror_dev/uw_live_projects/git_repo/eops/application/config.ru:3:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from /home/cgarndt/ror_dev/uw_live_projects/git_repo/eops/application/config.ru:in `new'
	from /home/cgarndt/ror_dev/uw_live_projects/git_repo/eops/application/config.ru:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
	from /usr/local/rvm/gems/ruby-2.1.6@eops/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

__An example of my database.yml file is__
```yaml
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_dev
  pool: 5
  host: dev.edu
  port: 0000
  username: <%= Chamber.db_u %>
  password: <%= Chamber.db_p %>
  socket: /var/run/mysqld/mysqld.sock
```

**Comment by sodabrew** [comment]
If I recall, Ubuntu 16.04 has removed SSL 3, so you must use TLS on both sides. If the database is still on Trusty, it's probably configured to expect SSL 3 clients.

**Comment by Chrisgo-75** [comment]
@sodabrew Thank you. Will meet with the server administrator tomorrow and look into the SSL 3 vs TLS network traffic.

**Comment by Chrisgo-75** [comment]
@sodabrew Since the network between the application and MySQL server is all internal, they are different boxes but within our Firewall, SSL is not needed from what I remember. Do I need to explicitly say in database.yml to not use SSL?

**Comment by Chrisgo-75** [comment]
@sodabrew well I installed Wireshark (first time) and when my VBox VM tries to spin up Rails app, Wireshark shows tcp connection of MySQL server sending back "Server Greeting Error 1129". NICE. Another baby-step forward in diagnosing the issue.

**Comment by Chrisgo-75** [comment]
@sodabrew Thank you for your feedback which gave direction in where to head. Met with server administrator and turned off SSL on Ubuntu 14.04 LTS since it was half-way enabled. Disabling SSL allowed Ubuntu 16.04 to make requests to Ubuntu 14.04.

It is nice to have feedback and help ... thank you sodabrew.

If anyone looks up this thread, I also needed to "FLUSH HOSTS" b/c MySQL server had blocked Ubuntu 16.04 IP Address.
