### ISSUE TITLE
Server restart hangs SSL connection on client

### ISSUE THREAD

**Issue by andreychernih** [brianmario/mysql2#876]
We've noticed that our Ruby workers are consuming lots of CPU without apparent reason. In fact, system's load average spikes from regular 0-1 to 20-30 because of this problem. I think this is somehow related to MySQL server restarts which have been happening frequently on our server. 

mysql2 version: 0.4.5
Ruby: ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
mysqld  Ver 5.6.35-81.0 for Linux on x86_64 (Percona Server (GPL), Release 81.0, Revision c96c427)

We connect to MySQL server over SSL using the following connection options:

```
            "database": "db",
            "host": "host",
            "password": "pass",
            "pool": "25",
            "tls": {
                "enabled": true,
                "sslca": "/etc/app-ssl/ca-cert.pem",
                "sslcapath": "/etc/app-ssl",
                "sslcert": "/etc/app-ssl/client-cert.pem",
                "sslcipher": "DHE-RSA-AES256-SHA",
                "sslkey": "/etc/app-ssl/client-key.pem",
                "sslverify": false
            },
            "username": "uname"
```

Below is what I've been able to extract from the running process.

Backtrace of the process (Ruby). I've captured the same trace a few times with significant pauses between tries, looks like the process is stuck in `Client#_query`. We wrap this call in `Timeout.timeout`, but it's not timing out, probably, because it's in the native code.

```
/home/jiff_user/.bundle_cache/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/home/jiff_user/.bundle_cache/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/home/jiff_user/.bundle_cache/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/jiff_user/.bundle_cache/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/storage_adapters/mysql/mysql2_client_wrapper.rb:31:in `method_missing_internal'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/storage_adapters/mysql/mysql2_client_wrapper.rb:18:in `method_missing'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:144:in `block in method_missing'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:131:in `with'
/home/jiff_user/.bundle_cache/gems/connection_pool-2.2.1/lib/connection_pool.rb:143:in `method_missing'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/storage_adapters/mysql.rb:125:in `run_query'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/apm/mysql_instrumentation.rb:34:in `block in run_sql_with_apm_instrumentation'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/apm/init.rb:67:in `trace'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/apm/mysql_instrumentation.rb:24:in `run_sql_with_apm_instrumentation'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_storage/storage_adapters/mysql.rb:120:in `query'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat_probes/mysql.rb:23:in `probe'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat_probes/base.rb:38:in `block in probe_with_error_handling'
/usr/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat_probes/base.rb:37:in `probe_with_error_handling'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:21:in `block in execute'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:20:in `collect'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:20:in `execute'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:16:in `initialize'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:115:in `new'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:115:in `block in execute'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/apm/init.rb:67:in `trace'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:112:in `execute'
/home/jiff_user/.bundle_cache/bundler/gems/jiff_support_rb-6828b5819966/lib/jiff_core/heartbeat.rb:180:in `block in ensure_thread'
```

Here's what gdb shows me:

```
#0  yaSSL::States::What (this=this@entry=0x7faa941107c0) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/extra/yassl/src/yassl_int.cpp:206
#1  0x00007faab8f36251 in yaSSL::SSL::GetError (this=this@entry=0x7faa9410fe50) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/extra/yassl/src/yassl_int.cpp:1515
#2  0x00007faab8f43e14 in yaSSL::receiveData (ssl=..., data=..., peek=peek@entry=false)
    at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/extra/yassl/src/handshake.cpp:1051
#3  0x00007faab8f2a00d in yaSSL::yaSSL_read (ssl=ssl@entry=0x7faa9410fe50, buffer=buffer@entry=0x7faa9410c160, sz=sz@entry=4)
    at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/extra/yassl/src/ssl.cpp:363
#4  0x00007faab8f090d6 in vio_ssl_read (vio=0x7faa94107f10, buf=0x7faa9410c160 "\t", size=<optimized out>)
    at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/vio/viossl.c:186
#5  0x00007faab8ee6153 in net_read_raw_loop (net=net@entry=0x7faa94104b00, count=4) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql/net_serv.cc:672
#6  0x00007faab8ee63f7 in net_read_packet_header (net=0x7faa94104b00) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql/net_serv.cc:762
#7  net_read_packet (net=0x7faa94104b00, complen=0x7faaa24e1020) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql/net_serv.cc:822
#8  0x00007faab8ee718c in my_net_read (net=net@entry=0x7faa94104b00) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql/net_serv.cc:899
#9  0x00007faab8edb1eb in cli_safe_read_with_ok (mysql=mysql@entry=0x7faa94104b00, parse_ok=parse_ok@entry=0 '\000', is_data_packet=is_data_packet@entry=0x0)
    at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql-common/client.c:1055
#10 0x00007faab8edb4ef in cli_safe_read (mysql=mysql@entry=0x7faa94104b00, is_data_packet=is_data_packet@entry=0x0)
    at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql-common/client.c:1188
#11 0x00007faab8edc4e8 in cli_read_query_result (mysql=0x7faa94104b00) at /export/home/pb2/build/sb_0-22759043-1489824007.71/rpm/BUILD/mysql-5.7.18/mysql-5.7.18/sql-common/client.c:5165
#12 0x00007faab94d12a9 in nogvl_read_query_result (ptr=<optimized out>) at client.c:507
#13 0x000000280c37e1a2 in call_without_gvl (func=func@entry=0x7faab94d12a0 <nogvl_read_query_result>, data1=0x7faa94104b00, ubf=<optimized out>, ubf@entry=0xffffffffffffffff, data2=<optimized out>,
    data2@entry=0x0, fail_if_interrupted=0) at thread.c:1270
#14 0x000000280c381265 in rb_thread_call_without_gvl (func=func@entry=0x7faab94d12a0 <nogvl_read_query_result>, data1=<optimized out>, ubf=ubf@entry=0xffffffffffffffff, data2=data2@entry=0x0)
    at thread.c:1380
#15 0x00007faab94d1d2c in rb_mysql_client_async_result (self=self@entry=172066065600) at client.c:554
#16 0x00007faab94d2e52 in rb_query (self=172066065600, sql=<optimized out>, current=172067214840) at client.c:763
#17 0x000000280c359f44 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7faaa25e4570, th=0x7faa94005420) at vm_insnhelper.c:1510
#18 vm_call_cfunc (th=0x7faa94005420, reg_cfp=0x7faaa25e4570, ci=<optimized out>) at vm_insnhelper.c:1600
#19 0x000000280c35ecf4 in vm_exec_core (th=th@entry=0x7faa94005420, initial=initial@entry=0) at insns.def:1025
#20 0x000000280c36295f in vm_exec (th=th@entry=0x7faa94005420) at vm.c:1427
#21 0x000000280c365b4a in invoke_block_from_c (th=0x7faa94005420, block=<optimized out>, self=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7faaa24e1758, blockptr=blockptr@entry=0x0,
    cref=cref@entry=0x0, defined_class=172065840360) at vm.c:817
#22 0x000000280c366c49 in vm_yield (argv=<optimized out>, argc=<optimized out>, th=<optimized out>) at vm.c:856
#23 rb_yield_0 (argv=<optimized out>, argc=<optimized out>) at vm_eval.c:944
#24 rb_yield (val=val@entry=8) at vm_eval.c:954
#25 0x000000280c37cada in rb_thread_s_handle_interrupt (self=<optimized out>, mask_arg=<optimized out>) at thread.c:1813
#26 0x000000280c359f44 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7faaa25e4610, th=0x7faa94005420) at vm_insnhelper.c:1510
#27 vm_call_cfunc (th=0x7faa94005420, reg_cfp=0x7faaa25e4610, ci=<optimized out>) at vm_insnhelper.c:1600
#28 0x000000280c35f635 in vm_exec_core (th=th@entry=0x7faa94005420, initial=initial@entry=0) at insns.def:996
#29 0x000000280c36295f in vm_exec (th=th@entry=0x7faa94005420) at vm.c:1427
#30 0x000000280c365b4a in invoke_block_from_c (th=0x7faa94005420, block=<optimized out>, self=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7faaa24e1d88, blockptr=blockptr@entry=0x0,
    cref=cref@entry=0x0, defined_class=172063863800) at vm.c:817
#31 0x000000280c366c49 in vm_yield (argv=<optimized out>, argc=<optimized out>, th=<optimized out>) at vm.c:856
#32 rb_yield_0 (argv=<optimized out>, argc=<optimized out>) at vm_eval.c:944
#33 rb_yield (val=val@entry=8) at vm_eval.c:954
#34 0x000000280c37cada in rb_thread_s_handle_interrupt (self=<optimized out>, mask_arg=<optimized out>) at thread.c:1813
#35 0x000000280c359f44 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7faaa25e47f0, th=0x7faa94005420) at vm_insnhelper.c:1510
#36 vm_call_cfunc (th=0x7faa94005420, reg_cfp=0x7faaa25e47f0, ci=<optimized out>) at vm_insnhelper.c:1600
#37 0x000000280c35f635 in vm_exec_core (th=th@entry=0x7faa94005420, initial=initial@entry=0) at insns.def:996
#38 0x000000280c36295f in vm_exec (th=th@entry=0x7faa94005420) at vm.c:1427
#39 0x000000280c365b4a in invoke_block_from_c (th=0x7faa94005420, block=<optimized out>, self=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7faaa24e23b8, blockptr=blockptr@entry=0x0,
    cref=cref@entry=0x0, defined_class=172063863800) at vm.c:817
#40 0x000000280c366c49 in vm_yield (argv=<optimized out>, argc=<optimized out>, th=<optimized out>) at vm.c:856
#41 rb_yield_0 (argv=<optimized out>, argc=<optimized out>) at vm_eval.c:944
#42 rb_yield (val=val@entry=8) at vm_eval.c:954
```

**Comment by sodabrew** [comment]
Coming back around for old tickets - This looks like an upstream bug in MySQL, my best advice is to make sure you're running the most recent client library and server available.

**Comment by sodabrew** [comment]
Were you able to resolve the issue?

**Comment by andreychernih** [comment]
Yes, this was resolved by updating to the latest mysql-common, mysql-devel and mysql-libs packages.
