### ISSUE TITLE
LoadError: incompatible library version

### ISSUE THREAD

**Issue by akitaonrails** [brianmario/mysql2#887]
I am running Manjaro Arch Linux (the most recent) and in there the default MySQL is MariaDB 10.1.26.

I have the following packages properly installed (and service up and running through systemd):

```
extra/libmariadbclient 10.1.26-1 [installed]
extra/mariadb 10.1.26-1 [installed]
extra/mariadb-clients 10.1.26-1 [installed]
```

I am using latest RVM and trying to run an old project with Ruby 2.2.7. But I am unable to load the `mysql2` gem even though I can successfully install it. I tried many different versions of mysql2 gem from 0.4.9, to 0.3.21 down to 0.3.18 and none loads. They all blow up like this:

```
$ bundle exec rake db:setup                                             [ruby-2.2.7]
rake aborted!
LoadError: incompatible library version - /home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/mysql2-0.3.18/lib/mysql2/mysql2.so
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `require'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
/home/akitaonrails/Sites/Codeminer42/peatio/config/application.rb:12:in `<top (required)>'
/home/akitaonrails/Sites/Codeminer42/peatio/Rakefile:5:in `require'
/home/akitaonrails/Sites/Codeminer42/peatio/Rakefile:5:in `<top (required)>'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `eval'
/home/akitaonrails/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

I tried to uninstall, reinstall, `gem pristine` and they all go fine like this:

```
$ gem install mysql2 -v 0.3.18                                          [ruby-2.2.7]
Fetching: mysql2-0.3.18.gem (100%)
Building native extensions.  This could take a while...
Successfully installed mysql2-0.3.18
1 gem installed
```

Tried the `gem install mysql2 -- --with-mysql-config=/usr/bin/mysql_config` again it installs fine, but when trying to load it still blows up.

Btw I tried going straight into the ext/ folder and running `ruby extconf.rb` to generate the Makefile again, then `make` to recompile to `.so` (and I manually deleted the previous .so to make sure), and still it doesn't load.

Anything I could be doing wrong?

**Comment by akitaonrails** [comment]
Interestingly, if I `rvm implode` and use `asdf` in it's place, now I can install ruby 2.3.4 (but not 2.2.7 for incompatible libyaml) and after installing the mysql2 gem it finally loads correctly, so maybe it's something specific to RVM?

**Comment by sodabrew** [comment]
Could you post the output from `ldd /home/akitaonrails/.rvm/gems/ruby-2.2.7/gems/mysql2-0.3.18/lib/mysql2/mysql2.so`

**Comment by gelanyia** [comment]
@sodabrew I have the same issue with ruby 2.2.7

```
ldd /home/gelanyia/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.9/lib/mysql2/mysql2.so
	linux-vdso.so.1 (0x00007fffb0b7d000)
	libruby.so.2.4 => /usr/lib/libruby.so.2.4 (0x00007f182dc90000)
	libmysqlclient.so.18 => /usr/lib/libmysqlclient.so.18 (0x00007f182d6fe000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f182d4e0000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f182d2c9000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f182cf7d000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f182cd79000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f182cb0f000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f182c68f000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f182c3fc000)
	libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007f182c1c4000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f182be0d000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f182e340000)
```

**Comment by sodabrew** [comment]
What package owns libmysqlclient.so.18? I think for Manjaro this will tell you:

```
$ pacman -Qo /usr/lib/libmysqlclient.so.18
```

**Comment by sodabrew** [comment]
Hello! Checking back in to see if you still see this problem?

**Comment by top1st** [comment]
```
ldd /home/ubuntu/rubykube/peatio/vendor/bundle/ruby/2.5.0/gems/mysql2-0.3.21/lib/mysql2/mysql2.so
        linux-vdso.so.1 =>  (0x00007fffa59d9000)
        libruby.so.2.5 => /home/ubuntu/.rvm/rubies/ruby-2.5.0/lib/libruby.so.2.5 (0x00007fd364268000)
        libmysqlclient.so.20 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20 (0x00007fd363c59000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd363a3c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd363672000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fd3633f2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd3631ee000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fd362fb6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd362cad000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd36499f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd362a93000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd362711000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd3624fb000)
```
```
 pacman -Qo /usr/lib/libmysqlclient.so.20
no display possible
```

**Comment by sodabrew** [comment]
@gelanyia I was thinking this was a libmysqlclient issue, but it's not. You're linked against the wrong Ruby:

```
ldd /home/gelanyia/.rvm/gems/ruby-2.2.7/gems/mysql2-0.4.9/lib/mysql2/mysql2.so
	linux-vdso.so.1 (0x00007fffb0b7d000)
	libruby.so.2.4 => /usr/lib/libruby.so.2.4 (0x00007f182dc90000)
```

Note that ldd says mysql2.so is linked to /usr/lib/libruby.so.2.4, but you should be linking against your rvm version of Ruby 2.2.7.

@top1st You haven't asked a question, and I don't see a problem, do you need assistance?
