### ISSUE TITLE
debian 9 installation

### ISSUE THREAD

**Issue by rubydesign** [brianmario/mysql2#964]
Hi,
it seems the library name that one needs to install on debian 9, has changed to 
default-libmysqlclient-dev

maybe nice for others to put it in that list 
T.

**Comment by rubydesign** [comment]
> apt-get install libmysqlclient-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmysqlclient-dev' has no installation candidate

**Comment by sodabrew** [comment]
Oh, I see why - Debian 9 is switching to MariaDB, so this is a compatibility shim.

**Comment by grezar** [comment]
@sodabrew 
Hi.
I coudn't install mysql2 even though I installed default-libmysqlclient-dev(and ruby-dev) in debian9.
```
$ cat /etc/debian_version
9.4
$ dpkg -l | grep default-libmysqlclient-dev
ii  default-libmysqlclient-dev:amd64  1.0.2                          amd64        MySQL database development files (metapackage)
$ gem install mysql2
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/mysql2-0.5.1/ext/mysql2
/usr/bin/ruby2.3 -r ./siteconf20180426-1486-1p3ma8p.rb extconf.rb
checking for rb_absint_size()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1051:in `block in have_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
	from extconf.rb:25:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/mysql2-0.5.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/mysql2-0.5.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/mysql2-0.5.1/gem_make.out
```

**Comment by sodabrew** [comment]
Install a compiler.

**Comment by grezar** [comment]
Oh... Thanks.
